# -*- coding: utf-8 -*-
"""
Company profiles for the five demo data rooms on venturethrust@gmail.com.

Everything here is invented. Every generated document carries a SAMPLE
footer so it can never be mistaken for a real company filing.
"""

PROFILES = [
    {
        "slug": "nellara-agrichain",
        "name": "Nellara AgriChain",
        "legal": "Nellara AgriChain Private Limited",
        "cin": "U01100KL2024PTC084912",
        "city": "Kozhikode, Kerala",
        "founded": "March 2024",
        "sector": "Agri supply chain",
        "founder_email": "nithin@nellaraagrichain.com",
        "one_line": "Farm to retail supply chain for Kerala produce.",
        "stage": "Seed",
        "ask": "Rs 6.0 crore",
        "post": "Rs 30 crore post money",
        "runway": "14 months",
        "founders": [
            ("Nithin Raveendran", "Co-founder and CEO",
             "Seven years at a national agri marketplace running the Kerala and coastal Karnataka "
             "category. Built the buyer side from 300 to 4,100 retailers. B.Tech, NIT Calicut."),
            ("Fahad Musthafa", "Co-founder and COO",
             "Third generation produce trader at Palayam market. Runs procurement across 34 farmer "
             "collectives in Wayanad and Malappuram. B.Com, Farook College."),
            ("Reshma Pillai", "Head of Cold Chain",
             "Nine years in temperature controlled logistics, last as regional operations lead for a "
             "listed cold chain operator. M.Tech in Food Process Engineering, TNAU."),
        ],
        "metrics": [
            ("Monthly GMV, July 2026", "Rs 1.42 crore"),
            ("Wastage rate", "7.4 percent, down from 22.1 percent"),
            ("Gross margin", "21.3 percent, up from 8.0 percent"),
            ("Retail accounts live", "61"),
            ("Hotel and restaurant accounts", "9 groups, 38 outlets"),
            ("Farmers supplying", "1,240 across 34 collectives"),
            ("Repeat order rate", "84 percent"),
            ("Monthly burn", "Rs 11.4 lakh"),
        ],
        "traction_rows": [
            ["Month", "GMV (Rs lakh)", "Gross margin %", "Wastage %", "Active buyers"],
            ["Feb 2026", "78", "9.1", "19.6", "34"],
            ["Mar 2026", "86", "11.4", "17.2", "39"],
            ["Apr 2026", "97", "14.0", "14.1", "44"],
            ["May 2026", "112", "16.8", "11.3", "51"],
            ["Jun 2026", "128", "19.2", "9.0", "57"],
            ["Jul 2026", "142", "21.3", "7.4", "61"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Nithin Raveendran", "Equity", "3,10,000", "31.0"],
            ["Fahad Musthafa", "Equity", "2,90,000", "29.0"],
            ["Reshma Pillai", "Equity", "1,00,000", "10.0"],
            ["Kerala Startup Mission (grant conversion)", "CCPS", "60,000", "6.0"],
            ["Angel round, Nov 2025 (7 investors)", "CCPS", "1,40,000", "14.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Account", "Type", "City", "Live since", "Monthly value (Rs)", "Payment terms"],
            ["Grand Hyatt Bolgatty", "Hotel", "Kochi", "Jan 2026", "4,10,000", "30 days"],
            ["Malabar Palace Group", "Hotel", "Kozhikode", "Nov 2025", "3,60,000", "30 days"],
            ["Paragon Restaurants", "Restaurant", "Kozhikode", "Dec 2025", "2,80,000", "21 days"],
            ["Nesto Hypermarket", "Retail", "Kochi", "Feb 2026", "6,20,000", "45 days"],
            ["Lulu Convenience", "Retail", "Kozhikode", "Apr 2026", "5,40,000", "45 days"],
            ["Kalyan Supermarkets", "Retail", "Thrissur", "Mar 2026", "3,10,000", "30 days"],
            ["Zam Zam Family Restaurant", "Restaurant", "Malappuram", "May 2026", "1,20,000", "14 days"],
            ["Fresh Point (12 kirana outlets)", "Retail", "Kozhikode", "Jun 2026", "2,40,000", "7 days"],
        ],
        "unit_rows": [
            ["SKU", "Buy price/kg", "Sell price/kg", "Wastage %", "Logistics/kg", "Contribution/kg"],
            ["Banana, Nendran", "38", "52", "5.2", "3.10", "8.02"],
            ["Tomato", "22", "34", "11.4", "3.10", "6.39"],
            ["Green chilli", "48", "72", "8.8", "3.40", "16.26"],
            ["Ginger", "62", "88", "3.1", "2.90", "20.37"],
            ["Cabbage", "18", "27", "9.6", "3.10", "3.31"],
            ["Curry leaf", "56", "92", "12.0", "3.60", "21.36"],
            ["Coconut", "26", "36", "1.8", "2.40", "7.13"],
        ],
        "risks": [
            "Produce prices swing week to week. We hold no inventory beyond 36 hours and reprice daily.",
            "Cold chain is our largest fixed cost. Two of the four vehicles are on lease, not owned.",
            "Buyer concentration: the top five accounts are 46 percent of GMV.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "zylo-health",
        "name": "Zylo Health",
        "legal": "Zylo Health Technologies Private Limited",
        "cin": "U72900KL2023PTC079344",
        "city": "Kochi, Kerala",
        "founded": "August 2023",
        "sector": "Medical imaging AI",
        "founder_email": "ann@zylohealth.in",
        "one_line": "AI assisted radiology triage for tier 2 and tier 3 hospitals.",
        "stage": "Seed",
        "ask": "Rs 8.0 crore",
        "post": "Rs 44 crore post money",
        "runway": "11 months",
        "founders": [
            ("Dr Ann Mary Varghese", "Co-founder and CEO",
             "Consultant radiologist for eleven years, last at a 750 bed teaching hospital. Read over "
             "90,000 studies. MD Radiodiagnosis, Amrita Institute of Medical Sciences."),
            ("Sreejith Nair", "Co-founder and CTO",
             "Six years building imaging models at a Mumbai medical AI company, including two products "
             "that cleared CDSCO. M.Tech Computer Vision, IIT Madras."),
            ("Dr Vivek Menon", "Head of Clinical Affairs",
             "Regulatory and clinical validation lead. Ran two prospective device studies to CDSCO "
             "submission. MBBS, DNB, plus a regulatory affairs certification."),
        ],
        "metrics": [
            ("Scans processed, July 2026", "46,200"),
            ("Hospitals live", "11, across Kerala and Tamil Nadu"),
            ("Contracted ARR", "Rs 1.87 crore"),
            ("Realised price per scan", "Rs 34"),
            ("Median time to flag a critical study", "48 seconds"),
            ("Sensitivity on internal validation set", "94.1 percent"),
            ("CDSCO Class B status", "Filed 14 April 2026, under review"),
            ("Monthly burn", "Rs 19.8 lakh"),
        ],
        "traction_rows": [
            ["Month", "Scans", "Hospitals", "Revenue (Rs lakh)", "Critical flags"],
            ["Feb 2026", "21,400", "6", "7.3", "412"],
            ["Mar 2026", "26,800", "7", "9.1", "533"],
            ["Apr 2026", "31,900", "8", "10.8", "611"],
            ["May 2026", "37,600", "9", "12.8", "742"],
            ["Jun 2026", "42,100", "10", "14.3", "816"],
            ["Jul 2026", "46,200", "11", "15.7", "889"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Dr Ann Mary Varghese", "Equity", "3,40,000", "34.0"],
            ["Sreejith Nair", "Equity", "2,60,000", "26.0"],
            ["Dr Vivek Menon", "Equity", "80,000", "8.0"],
            ["Pre seed, Feb 2025 (2 angels)", "CCPS", "1,20,000", "12.0"],
            ["Amrita TBI (grant conversion)", "CCPS", "50,000", "5.0"],
            ["ESOP pool (reserved)", "Options", "1,50,000", "15.0"],
        ],
        "customers": [
            ["Hospital", "Beds", "State", "Live since", "Scans/month", "Contract value (Rs/yr)"],
            ["Sunrise Hospital, Kakkanad", "180", "Kerala", "Nov 2025", "6,200", "25,29,600"],
            ["Lakeshore Extension, Maradu", "120", "Kerala", "Dec 2025", "4,800", "19,58,400"],
            ["MIMS Kottakkal", "210", "Kerala", "Jan 2026", "7,100", "28,96,800"],
            ["KMCT Medical, Kozhikode", "300", "Kerala", "Feb 2026", "8,400", "34,27,200"],
            ["Sree Uthradom, Trivandrum", "140", "Kerala", "Mar 2026", "3,900", "15,91,200"],
            ["Kauvery Hospital, Salem", "160", "Tamil Nadu", "Apr 2026", "4,600", "18,76,800"],
            ["Vijaya Medical, Erode", "90", "Tamil Nadu", "Jun 2026", "2,700", "11,01,600"],
            ["Four district hospitals (pilot)", "-", "Kerala", "Jul 2026", "8,500", "Pilot, unbilled"],
        ],
        "unit_rows": [
            ["Line item", "Per scan (Rs)", "Notes"],
            ["Price realised", "34.00", "Blended across annual contracts"],
            ["GPU inference cost", "2.40", "Batched, spot capacity"],
            ["Storage and transfer", "0.90", "90 day retention, then archive"],
            ["Radiologist audit sampling", "3.10", "8 percent of studies re read"],
            ["Support and account management", "1.80", "Allocated"],
            ["Gross contribution", "25.80", "75.9 percent gross margin"],
        ],
        "risks": [
            "CDSCO Class B clearance is pending. Commercial scale up outside pilots depends on it.",
            "Radiologist trust is earned per hospital. Sales cycle averages 94 days.",
            "Model drift across scanner vendors requires per site calibration in the first 30 days.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "voltaneer",
        "name": "Voltaneer",
        "legal": "Voltaneer Energy Systems Private Limited",
        "cin": "U31900TZ2023PTC039771",
        "city": "Coimbatore, Tamil Nadu",
        "founded": "June 2023",
        "sector": "Industrial IoT and energy",
        "founder_email": "karthik@voltaneer.in",
        "one_line": "Energy monitoring for small and mid sized factories.",
        "stage": "Seed",
        "ask": "Rs 7.0 crore",
        "post": "Rs 38 crore post money",
        "runway": "13 months",
        "founders": [
            ("Karthik Subramanian", "Co-founder and CEO",
             "Twelve years in industrial power electronics, last as India applications head for a "
             "global drives manufacturer. B.E. Electrical, PSG Tech."),
            ("Aravind Rangaswamy", "Co-founder and CTO",
             "Embedded systems and edge analytics. Previously built metering firmware shipped on "
             "40,000 units. M.S. Electrical Engineering, Arizona State."),
            ("Divya Balan", "VP Sales",
             "Nine years selling capital equipment into Coimbatore and Tiruppur clusters. Carried and "
             "exceeded a Rs 12 crore annual quota. MBA, Bharathiar University."),
        ],
        "metrics": [
            ("ARR, July 2026", "Rs 2.34 crore"),
            ("Recurring share of revenue", "47 percent, up from 24 percent"),
            ("Median sales cycle", "71 days, down from 264 days"),
            ("Factories monitored", "88"),
            ("Average verified saving per factory", "8.4 percent of the power bill"),
            ("Net revenue retention", "118 percent"),
            ("Logo churn, trailing 12 months", "6 percent"),
            ("Monthly burn", "Rs 16.2 lakh"),
        ],
        "traction_rows": [
            ["Month", "ARR (Rs lakh)", "Factories", "Recurring %", "Median cycle (days)"],
            ["Feb 2026", "142", "58", "27", "212"],
            ["Mar 2026", "158", "63", "31", "186"],
            ["Apr 2026", "176", "69", "36", "148"],
            ["May 2026", "197", "76", "40", "112"],
            ["Jun 2026", "216", "82", "44", "88"],
            ["Jul 2026", "234", "88", "47", "71"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Karthik Subramanian", "Equity", "3,20,000", "32.0"],
            ["Aravind Rangaswamy", "Equity", "2,80,000", "28.0"],
            ["Divya Balan", "Equity", "70,000", "7.0"],
            ["Angel round, Mar 2025 (5 investors)", "CCPS", "1,60,000", "16.0"],
            ["Strategic angel, distribution partner", "CCPS", "50,000", "5.0"],
            ["ESOP pool (reserved)", "Options", "1,20,000", "12.0"],
        ],
        "customers": [
            ["Factory", "Sector", "Cluster", "Live since", "Annual subscription (Rs)", "Verified saving"],
            ["Sri Kumaran Textiles", "Spinning", "Tiruppur", "Sep 2025", "3,60,000", "9.1 percent"],
            ["Precision Castings Ltd", "Foundry", "Coimbatore", "Oct 2025", "4,20,000", "11.4 percent"],
            ["Anand Pumps", "Pumps", "Coimbatore", "Nov 2025", "3,00,000", "7.2 percent"],
            ["Vetri Knits", "Knitwear", "Tiruppur", "Jan 2026", "2,40,000", "8.8 percent"],
            ["Sakthi Auto Components", "Auto parts", "Erode", "Feb 2026", "4,80,000", "6.9 percent"],
            ["Nachimuthu Mills", "Spinning", "Pollachi", "Mar 2026", "3,60,000", "10.2 percent"],
            ["KG Denim (unit 2)", "Textiles", "Coimbatore", "May 2026", "5,40,000", "7.8 percent"],
            ["Suguna Feeds, plant 4", "Food processing", "Udumalpet", "Jun 2026", "4,20,000", "8.0 percent"],
        ],
        "unit_rows": [
            ["Line item", "Per factory, year 1 (Rs)", "Per factory, year 2 (Rs)"],
            ["Software subscription", "2,40,000", "2,64,000"],
            ["Sensor hardware (one time)", "1,10,000", "0"],
            ["Installation and commissioning", "35,000", "0"],
            ["Hardware cost of goods", "-62,000", "0"],
            ["Install labour", "-21,000", "0"],
            ["Cloud and connectivity", "-18,000", "-19,000"],
            ["Support", "-24,000", "-24,000"],
            ["Contribution", "2,60,000", "2,21,000"],
        ],
        "risks": [
            "Hardware still gates every new deployment and carries a 9 week lead time on two components.",
            "Capex approval remains the slowest step at factories above 200 employees.",
            "Savings claims are audited by the customer's own meter. One disputed claim can stall a cluster.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "aegis-drone-systems",
        "name": "Aegis Drone Systems",
        "legal": "Aegis Drone Systems Private Limited",
        "cin": "U74999KL2024PTC086220",
        "city": "Kochi, Kerala",
        "founded": "January 2024",
        "sector": "Industrial inspection",
        "founder_email": "rohan@aegisdronesystems.in",
        "one_line": "Drone inspection for ports, transmission lines and plantation estates.",
        "stage": "Seed",
        "ask": "Rs 5.5 crore",
        "post": "Rs 26 crore post money",
        "runway": "9 months",
        "founders": [
            ("Rohan Fernandes", "Co-founder and CEO",
             "Five years at a Bengaluru drone services company, last running the industrial inspection "
             "vertical across four states. B.E. Aeronautical, MIT Manipal."),
            ("Capt. Ismail Haq", "Co-founder and Chief Pilot",
             "Eighteen years flying with the Indian Air Force, then civil UAS instructor. DGCA "
             "certified remote pilot instructor, 1,900 logged UAS hours."),
            ("Meera Nambiar", "Head of Analytics",
             "Computer vision for defect detection. Previously built rail track inspection models for "
             "a public sector client. M.Tech, CUSAT."),
        ],
        "metrics": [
            ("Revenue, FY26", "Rs 1.10 crore"),
            ("Inspection cycles delivered", "46"),
            ("Sites under annual retainer", "0 signed, 3 in negotiation"),
            ("Repeat customers", "2 of 14"),
            ("Average project value", "Rs 2.39 lakh"),
            ("Defect detection precision, internal set", "88.6 percent"),
            ("DGCA BVLOS status", "Applied 2 March 2026, pending"),
            ("Monthly burn", "Rs 9.6 lakh"),
        ],
        "traction_rows": [
            ["Quarter", "Projects", "Revenue (Rs lakh)", "Repeat %", "Retainers signed"],
            ["Q1 FY26", "6", "13", "0", "0"],
            ["Q2 FY26", "9", "21", "11", "0"],
            ["Q3 FY26", "13", "31", "15", "0"],
            ["Q4 FY26", "18", "45", "17", "0"],
            ["Q1 FY27", "11", "28", "18", "0"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Rohan Fernandes", "Equity", "3,60,000", "36.0"],
            ["Capt. Ismail Haq", "Equity", "2,80,000", "28.0"],
            ["Meera Nambiar", "Equity", "1,10,000", "11.0"],
            ["Friends and family, Jun 2025", "CCPS", "90,000", "9.0"],
            ["Kerala Startup Mission (grant conversion)", "CCPS", "60,000", "6.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Client", "Asset type", "Location", "Engagement", "Value (Rs)", "Repeat"],
            ["Cochin Port Authority", "Wharf and cranes", "Kochi", "Mar 2026", "6,40,000", "Yes"],
            ["KSEB transmission circle", "132 kV lines", "Thrissur", "Feb 2026", "4,10,000", "No"],
            ["Harrisons Malayalam", "Tea estate survey", "Idukki", "Apr 2026", "2,80,000", "Yes"],
            ["Adani Vizhinjam (vendor trial)", "Breakwater", "Trivandrum", "May 2026", "3,20,000", "No"],
            ["AVT Plantations", "Rubber estate", "Kottayam", "Jan 2026", "1,90,000", "No"],
            ["Kerala Water Authority", "Overhead tanks", "Kochi", "Jun 2026", "1,40,000", "No"],
            ["BPCL Kochi Refinery (trial)", "Flare stack", "Kochi", "Jul 2026", "2,60,000", "No"],
        ],
        "unit_rows": [
            ["Line item", "Per inspection cycle (Rs)", "Notes"],
            ["Project fee", "2,39,000", "Average across 46 cycles"],
            ["Crew, two people, three days", "-46,000", "Pilot plus spotter"],
            ["Travel and site access", "-21,000", "Includes permits"],
            ["Equipment depreciation", "-28,000", "Airframe and payload"],
            ["Insurance", "-9,000", "Per sortie rider"],
            ["Analytics and reporting", "-34,000", "Two analyst days"],
            ["Contribution", "1,01,000", "42.3 percent"],
        ],
        "risks": [
            "Revenue is project based. Nothing recurs until a retainer is signed.",
            "BVLOS clearance gates the transmission line business, which is the largest pipeline.",
            "One airframe loss would remove roughly a third of current flying capacity.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "kadal-systems",
        "name": "Kadal Systems",
        "legal": "Kadal Systems Private Limited",
        "cin": "U31909KL2023PTC081455",
        "city": "Kollam, Kerala",
        "founded": "May 2023",
        "sector": "Marine safety IoT",
        "founder_email": "sujith@kadalsystems.in",
        "one_line": "Satellite messaging and distress alerts for small fishing vessels.",
        "stage": "Seed",
        "ask": "Rs 4.5 crore",
        "post": "Rs 22 crore post money",
        "runway": "10 months",
        "founders": [
            ("Sujith Kumar", "Co-founder and CEO",
             "Marine engineer, eight years at sea and four building vessel electronics. Grew up in a "
             "fishing family in Neendakara. B.Tech Marine Engineering, CUSAT."),
            ("Anas Rahman", "Co-founder and CTO",
             "RF and satellite communications. Previously designed terminals for a maritime tracking "
             "provider. M.Tech Communication Systems, NIT Calicut."),
            ("Lakshmi Menon", "Head of Field Operations",
             "Ran a state fisheries extension programme across three districts. Knows every harbour "
             "society officer from Kollam to Alappuzha. MSW, Loyola Trivandrum."),
        ],
        "metrics": [
            ("Units deployed", "3,100"),
            ("Units bought at full price, no subsidy", "240"),
            ("Units under state subsidy scheme", "2,860"),
            ("Annual connectivity subscription", "Rs 1,800 per vessel"),
            ("Subscription renewal rate, year 2", "71 percent"),
            ("Distress alerts relayed", "37, including 9 rescues"),
            ("Hardware gross margin", "31 percent"),
            ("Monthly burn", "Rs 8.1 lakh"),
        ],
        "traction_rows": [
            ["Quarter", "Units shipped", "Full price units", "Subscription base", "Revenue (Rs lakh)"],
            ["Q1 FY26", "410", "12", "980", "31"],
            ["Q2 FY26", "620", "28", "1,540", "44"],
            ["Q3 FY26", "740", "51", "2,180", "56"],
            ["Q4 FY26", "880", "84", "2,760", "68"],
            ["Q1 FY27", "450", "65", "3,100", "39"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Sujith Kumar", "Equity", "3,50,000", "35.0"],
            ["Anas Rahman", "Equity", "3,00,000", "30.0"],
            ["Lakshmi Menon", "Equity", "90,000", "9.0"],
            ["Angel round, Aug 2025 (4 investors)", "CCPS", "1,10,000", "11.0"],
            ["Maritime India grant (conversion)", "CCPS", "50,000", "5.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Channel", "District", "Units", "Subsidy", "Full price", "Renewals due FY27"],
            ["Neendakara harbour society", "Kollam", "820", "760", "60", "640"],
            ["Sakthikulangara society", "Kollam", "540", "500", "40", "410"],
            ["Munambam boat owners", "Ernakulam", "610", "560", "50", "470"],
            ["Beypore association", "Kozhikode", "430", "400", "30", "300"],
            ["Vizhinjam society", "Trivandrum", "380", "350", "30", "260"],
            ["Direct sales, boat owners", "Multiple", "240", "0", "240", "180"],
            ["Ponnani society (pilot)", "Malappuram", "80", "290", "0", "0"],
        ],
        "unit_rows": [
            ["Line item", "Per unit (Rs)", "Notes"],
            ["Device price, full", "14,500", "Subsidised price to owner is Rs 3,600"],
            ["Bill of materials", "-8,200", "Terminal, antenna, enclosure"],
            ["Assembly and testing", "-1,100", "In house, Kollam"],
            ["Installation on vessel", "-900", "Field team"],
            ["Warranty provision", "-800", "24 months"],
            ["Hardware contribution", "3,500", "24.1 percent"],
            ["Annual connectivity subscription", "1,800", "Airtime cost Rs 640, margin 64 percent"],
        ],
        "risks": [
            "Almost all demand to date came through a state subsidy scheme with an annual budget cycle.",
            "Satellite airtime is bought from a single provider on a one year contract.",
            "Monsoon months, June to August, are close to zero for new installations.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# NEW INBOUND, not yet opened and not yet on the watchlist.
#
# Sector chosen against what the bootcamp mentors actually back:
#   Malabar Angel Network (PK Gopalakrishnan): agri, cleantech, healthcare,
#     education, IT, social impact in Kerala. Portfolio includes Farmers Fresh
#     Zone, Clootrack, SP Robotic Works, TIEA Connectors, Woolly Farms,
#     Powerbot, Skylark Drones, RoshAi, Cureous Labs.
#   CITI 2.0 (Ajayan K Anat): AI and ML, IT infrastructure, telecom, health
#     tech, creative tech, food and agro tech, tier 2 job creation.
#   Ashutosh Vikram: agri supply chain, Bengaluru.
#   Ashish Ranjan, LH2 AI Labs: domain expert data for frontier model training.
# ─────────────────────────────────────────────────────────────────────────────

NEW_PROFILES = [
    {
        "slug": "anvaya-ai",
        "name": "Anvaya AI",
        "legal": "Anvaya AI Private Limited",
        "cin": "U62013KL2025PTC091204",
        "city": "Kochi, Kerala",
        "founded": "February 2025",
        "sector": "AI training data",
        "founder_email": "nandita@anvaya-ai.in",
        "one_line": "Expert reviewed Indian clinical and legal data for frontier model training.",
        "stage": "Seed",
        "ask": "Rs 9.0 crore",
        "post": "Rs 48 crore post money",
        "runway": "12 months",
        "founders": [
            ("Nandita Rajagopal", "Co-founder and CEO",
             "Six years building data operations for a US labelling company, last running the "
             "medical vertical with 400 reviewers. M.Tech, IIT Madras."),
            ("Basil Thomas", "Co-founder and CTO",
             "Machine learning infrastructure. Built the evaluation harness used across three model "
             "releases at a Bengaluru AI lab. B.Tech, NIT Calicut."),
            ("Adv. Shruti Nayar", "Head of Legal Domain",
             "Eleven years litigating in the Kerala High Court. Runs the panel of 140 advocates who "
             "review the legal corpus. LLM, NUALS Kochi."),
        ],
        "metrics": [
            ("Contracted ARR, July 2026", "Rs 3.10 crore"),
            ("Frontier lab customers", "3, two US and one India"),
            ("Expert reviewers on panel", "612 doctors and 140 advocates"),
            ("Reviewed items delivered", "1.84 million"),
            ("Inter annotator agreement", "0.89 Cohen kappa"),
            ("Blended price per reviewed item", "Rs 41"),
            ("Gross margin", "58 percent"),
            ("Monthly burn", "Rs 24.6 lakh"),
        ],
        "traction_rows": [
            ["Month", "Items delivered", "Revenue (Rs lakh)", "Reviewers active", "Rejection rate %"],
            ["Feb 2026", "94,000", "18", "214", "9.1"],
            ["Mar 2026", "142,000", "26", "308", "7.8"],
            ["Apr 2026", "186,000", "34", "402", "6.4"],
            ["May 2026", "241,000", "44", "511", "5.2"],
            ["Jun 2026", "288,000", "53", "588", "4.6"],
            ["Jul 2026", "324,000", "61", "752", "4.1"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Nandita Rajagopal", "Equity", "3,20,000", "32.0"],
            ["Basil Thomas", "Equity", "2,90,000", "29.0"],
            ["Adv. Shruti Nayar", "Equity", "90,000", "9.0"],
            ["Pre seed, Sep 2025 (3 angels)", "CCPS", "1,50,000", "15.0"],
            ["ESOP pool (reserved)", "Options", "1,50,000", "15.0"],
        ],
        "customers": [
            ["Customer", "Vertical", "Region", "Live since", "Annual value (Rs)", "Status"],
            ["Frontier lab A (named under NDA)", "Medical reasoning", "United States",
             "Nov 2025", "1,42,00,000", "Renewed"],
            ["Frontier lab B (named under NDA)", "Legal reasoning", "United States",
             "Feb 2026", "1,08,00,000", "Live"],
            ["Indian foundation model team", "Multilingual medical", "India",
             "May 2026", "60,00,000", "Live"],
            ["Two evaluation pilots", "Coding and agentic", "United States",
             "Jul 2026", "Pilot, unbilled", "In pilot"],
        ],
        "unit_rows": [
            ["Line item", "Per reviewed item (Rs)", "Notes"],
            ["Price realised", "41.00", "Blended across medical and legal"],
            ["Expert reviewer fee", "-14.20", "Paid per item, not per hour"],
            ["Second pass adjudication", "-2.10", "On 18 percent of items"],
            ["Platform and storage", "-0.90", "Indian cloud region"],
            ["Programme management", "-1.60", "Allocated"],
            ["Gross contribution", "22.20", "54.1 percent"],
        ],
        "risks": [
            "Three customers are 92 percent of revenue and frontier lab budgets move fast in both directions.",
            "Reviewer supply is the constraint. Doctors leave when hospital rosters get heavy.",
            "Any shift toward synthetic data at the labs would compress this market quickly.",
        ],
        "docs_note": "Sent to investors, July 2026.",
    },
    {
        "slug": "thooval-studios",
        "name": "Thooval Studios",
        "legal": "Thooval Studios Private Limited",
        "cin": "U59120KL2024PTC088417",
        "city": "Kozhikode, Kerala",
        "founded": "July 2024",
        "sector": "Creative technology",
        "founder_email": "rahul@thoovalstudios.com",
        "one_line": "AI assisted dubbing and subtitling for Indian language streaming.",
        "stage": "Seed",
        "ask": "Rs 6.5 crore",
        "post": "Rs 32 crore post money",
        "runway": "10 months",
        "founders": [
            ("Rahul Panicker", "Co-founder and CEO",
             "Nine years in post production, last as head of localisation delivery for a Chennai "
             "studio serving three national OTT platforms."),
            ("Divya Krishnan", "Co-founder and CTO",
             "Speech synthesis and voice conversion. Published on low resource Indian language TTS. "
             "M.S. by Research, IIIT Hyderabad."),
            ("Ameer Haris", "Head of Creative",
             "Dubbing director for fourteen feature releases across Malayalam, Tamil and Telugu. "
             "Runs the panel of 90 voice artists."),
        ],
        "metrics": [
            ("Contracted ARR, July 2026", "Rs 1.64 crore"),
            ("Hours of content delivered", "4,180"),
            ("Languages supported", "9 Indian languages plus English"),
            ("Turnaround per episode hour", "31 hours, against an industry 6 to 9 days"),
            ("Cost per finished hour", "Rs 38,000, against Rs 1.4 lakh traditional"),
            ("Voice artists on panel", "90, all under consent and royalty agreements"),
            ("Platform customers", "4 OTT platforms, 11 production houses"),
            ("Monthly burn", "Rs 14.2 lakh"),
        ],
        "traction_rows": [
            ["Month", "Hours delivered", "Revenue (Rs lakh)", "Languages", "Repeat customers"],
            ["Feb 2026", "310", "7.4", "5", "3"],
            ["Mar 2026", "402", "9.6", "6", "5"],
            ["Apr 2026", "518", "12.1", "7", "7"],
            ["May 2026", "640", "14.8", "8", "9"],
            ["Jun 2026", "742", "16.9", "9", "11"],
            ["Jul 2026", "868", "19.4", "9", "13"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Rahul Panicker", "Equity", "3,40,000", "34.0"],
            ["Divya Krishnan", "Equity", "3,00,000", "30.0"],
            ["Ameer Haris", "Equity", "1,00,000", "10.0"],
            ["Angel round, Jan 2026 (4 investors)", "CCPS", "1,20,000", "12.0"],
            ["Kerala Startup Mission (grant conversion)", "CCPS", "40,000", "4.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Customer", "Type", "Languages", "Live since", "Annual value (Rs)", "Repeat"],
            ["National OTT platform 1", "Streaming", "7", "Oct 2025", "48,00,000", "Yes"],
            ["National OTT platform 2", "Streaming", "5", "Jan 2026", "36,00,000", "Yes"],
            ["Regional OTT, Kerala", "Streaming", "4", "Dec 2025", "22,00,000", "Yes"],
            ["Regional OTT, Karnataka", "Streaming", "3", "Apr 2026", "18,00,000", "Yes"],
            ["Seven production houses", "Film and series", "9", "Various", "31,00,000", "Mixed"],
            ["Two ed tech publishers", "Course content", "6", "May 2026", "9,00,000", "Yes"],
        ],
        "unit_rows": [
            ["Line item", "Per finished hour (Rs)", "Traditional studio (Rs)"],
            ["Price to customer", "38,000", "1,40,000"],
            ["Voice artist fees and royalty", "-11,200", "-52,000"],
            ["Creative direction and QC", "-6,400", "-28,000"],
            ["Compute for synthesis", "-2,100", "0"],
            ["Studio time and mixing", "-3,800", "-34,000"],
            ["Gross contribution", "14,500", "26,000"],
        ],
        "risks": [
            "Voice artist consent and royalty is the whole trust model. One dispute would be public and damaging.",
            "OTT localisation budgets are renegotiated annually and platform consolidation is a real risk.",
            "Open source speech models are improving fast, which compresses the technical moat toward creative direction.",
        ],
        "docs_note": "Sent to investors, July 2026.",
    },
    {
        "slug": "kalpana-robotics",
        "name": "Kalpana Robotics",
        "legal": "Kalpana Robotics Private Limited",
        "cin": "U85499KL2024PTC087163",
        "city": "Kozhikode, Kerala",
        "founded": "April 2024",
        "sector": "Skilling and education",
        "founder_email": "sreelakshmi@kalpanarobotics.in",
        "one_line": "Placement linked robotics and embedded training for tier 2 engineering colleges.",
        "stage": "Seed",
        "ask": "Rs 5.0 crore",
        "post": "Rs 24 crore post money",
        "runway": "11 months",
        "founders": [
            ("Sreelakshmi Menon", "Co-founder and CEO",
             "Seven years placing engineers into embedded roles, last running campus hiring for an "
             "automotive electronics supplier. B.Tech, GEC Thrissur."),
            ("Vishnu Prasad", "Co-founder and Head of Curriculum",
             "Embedded firmware engineer turned trainer. Built the lab curriculum now running in "
             "34 colleges. M.Tech, NIT Calicut."),
            ("Jerin Sebastian", "Head of Employer Partnerships",
             "Six years in staffing for electronics manufacturing across Coimbatore and Kochi."),
        ],
        "metrics": [
            ("Contracted ARR, July 2026", "Rs 2.06 crore"),
            ("Colleges under contract", "34, across Kerala and Tamil Nadu"),
            ("Students trained to date", "4,820"),
            ("Placement rate on the placement track", "71 percent within 6 months"),
            ("Median first salary", "Rs 4.6 lakh, up from a Rs 2.8 lakh campus baseline"),
            ("Employer partners hiring", "46"),
            ("College renewal rate", "88 percent"),
            ("Monthly burn", "Rs 12.4 lakh"),
        ],
        "traction_rows": [
            ["Term", "Colleges", "Students", "Revenue (Rs lakh)", "Placed", "Placement %"],
            ["Odd 2024", "6", "410", "18", "212", "52"],
            ["Even 2025", "11", "780", "34", "444", "57"],
            ["Odd 2025", "19", "1,240", "58", "769", "62"],
            ["Even 2026", "27", "1,610", "82", "1,062", "66"],
            ["Odd 2026", "34", "2,180", "106", "In progress", "71 to date"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Sreelakshmi Menon", "Equity", "3,30,000", "33.0"],
            ["Vishnu Prasad", "Equity", "3,00,000", "30.0"],
            ["Jerin Sebastian", "Equity", "90,000", "9.0"],
            ["Angel round, Oct 2025 (5 investors)", "CCPS", "1,30,000", "13.0"],
            ["ESOP pool (reserved)", "Options", "1,50,000", "15.0"],
        ],
        "customers": [
            ["College", "District", "Students per term", "Live since", "Annual fee (Rs)", "Renewed"],
            ["Govt Engineering College, Kozhikode", "Kozhikode", "180", "Aug 2024", "9,00,000", "Yes"],
            ["MES College of Engineering", "Malappuram", "160", "Aug 2024", "8,00,000", "Yes"],
            ["Vidya Academy", "Thrissur", "140", "Jan 2025", "7,00,000", "Yes"],
            ["Rajagiri School of Engineering", "Ernakulam", "210", "Aug 2025", "10,50,000", "Yes"],
            ["KMEA Engineering College", "Ernakulam", "120", "Jan 2026", "6,00,000", "First term"],
            ["Kongu Engineering College", "Erode", "190", "Jan 2026", "9,50,000", "First term"],
            ["Twenty eight further colleges", "Various", "1,180", "Various", "56,00,000", "Mixed"],
        ],
        "unit_rows": [
            ["Line item", "Per student (Rs)", "Notes"],
            ["College fee per student per term", "4,860", "Billed to the institution, not the student"],
            ["Trainer cost", "-1,640", "Trainer covers 40 students"],
            ["Lab kit amortisation", "-720", "Kits are ours, three year life"],
            ["Placement operations", "-540", "Employer side effort"],
            ["Platform and content", "-280", "Allocated"],
            ["Gross contribution", "1,680", "34.6 percent"],
        ],
        "risks": [
            "College budgets are set once a year and a bad placement season costs several renewals at once.",
            "Placement rate is the product. Any hiring slowdown in electronics hits the headline number directly.",
            "Trainer recruitment in tier 2 towns is slow and is the current growth constraint.",
        ],
        "docs_note": "Sent to investors, July 2026.",
    },
    {
        "slug": "metricon-interconnect",
        "name": "Metricon Interconnect",
        "legal": "Metricon Interconnect Private Limited",
        "cin": "U31909TZ2023PTC041882",
        "city": "Coimbatore, Tamil Nadu",
        "founded": "November 2023",
        "sector": "Electronics manufacturing",
        "founder_email": "ramesh@metricon-interconnect.in",
        "one_line": "Precision connectors for electric vehicles and industrial automation.",
        "stage": "Seed",
        "ask": "Rs 8.5 crore",
        "post": "Rs 40 crore post money",
        "runway": "12 months",
        "founders": [
            ("Ramesh Venkataraman", "Co-founder and CEO",
             "Sixteen years in connector manufacturing, last as plant head for an Indian subsidiary "
             "of a Japanese connector maker. B.E. Mechanical, GCT Coimbatore."),
            ("Priya Sundaram", "Co-founder and Head of Engineering",
             "Tooling and materials. Holds two granted design registrations on high current "
             "terminal geometry. M.Tech, IIT Madras."),
            ("Naveen Kumar", "Head of Quality",
             "Ten years in automotive quality systems. Took two plants through IATF 16949."),
        ],
        "metrics": [
            ("Revenue, FY26", "Rs 6.40 crore"),
            ("Run rate, July 2026", "Rs 9.80 crore annualised"),
            ("Parts approved by customers", "41 part numbers across 9 customers"),
            ("EV share of revenue", "58 percent, up from 21 percent"),
            ("Gross margin", "34 percent"),
            ("Parts per million defect rate", "184, against a 500 customer limit"),
            ("Import substitution per part", "22 to 31 percent below landed Chinese cost"),
            ("Monthly burn", "Rs 9.20 lakh, EBITDA near breakeven"),
        ],
        "traction_rows": [
            ["Quarter", "Revenue (Rs lakh)", "EV share %", "Part numbers", "PPM defects"],
            ["Q1 FY26", "112", "21", "18", "412"],
            ["Q2 FY26", "138", "29", "24", "338"],
            ["Q3 FY26", "176", "38", "31", "266"],
            ["Q4 FY26", "214", "49", "36", "211"],
            ["Q1 FY27", "245", "58", "41", "184"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Ramesh Venkataraman", "Equity", "3,10,000", "31.0"],
            ["Priya Sundaram", "Equity", "2,70,000", "27.0"],
            ["Naveen Kumar", "Equity", "70,000", "7.0"],
            ["Angel round, May 2025 (6 investors)", "CCPS", "1,80,000", "18.0"],
            ["Machinery lender warrant", "Warrant", "70,000", "7.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Customer", "Segment", "Location", "Approved since", "Annual value (Rs)", "Part numbers"],
            ["EV two wheeler OEM", "Electric vehicle", "Hosur", "Mar 2025", "2,10,00,000", "11"],
            ["Battery pack assembler", "Electric vehicle", "Bengaluru", "Jul 2025", "1,60,00,000", "8"],
            ["Industrial drives maker", "Automation", "Coimbatore", "Jan 2025", "1,20,00,000", "7"],
            ["Charging equipment maker", "Electric vehicle", "Chennai", "Nov 2025", "94,00,000", "5"],
            ["Pump and motor manufacturer", "Automation", "Coimbatore", "Aug 2024", "72,00,000", "4"],
            ["Four smaller accounts", "Mixed", "Various", "Various", "84,00,000", "6"],
        ],
        "unit_rows": [
            ["Line item", "Per 1,000 units (Rs)", "Notes"],
            ["Price realised", "41,200", "Blended across 41 part numbers"],
            ["Raw material, copper and polymer", "-19,800", "Copper is 61 percent of material cost"],
            ["Moulding and stamping", "-4,600", "In house since Q3 FY26"],
            ["Plating, outsourced", "-2,900", "Single vendor in Coimbatore"],
            ["Assembly and test", "-3,700", "Semi automated"],
            ["Scrap and rework", "-1,100", "Down from Rs 3,400 in FY25"],
            ["Gross contribution", "9,100", "22.1 percent at part level"],
        ],
        "risks": [
            "Copper price moves straight through the P and L and contracts reprice only twice a year.",
            "Plating is outsourced to a single vendor, which is a real single point of failure.",
            "Automotive qualification takes 9 to 14 months, so growth is slow to start and hard to stop.",
        ],
        "docs_note": "Sent to investors, July 2026.",
    },
    {
        "slug": "puzha-foods",
        "name": "Puzha Foods",
        "legal": "Puzha Foods Private Limited",
        "cin": "U15490KL2024PTC085539",
        "city": "Thrissur, Kerala",
        "founded": "February 2024",
        "sector": "Food and agro processing",
        "founder_email": "anjali@puzhafoods.in",
        "one_line": "Minimally processed Kerala produce for modern trade and direct to consumer.",
        "stage": "Seed",
        "ask": "Rs 5.5 crore",
        "post": "Rs 27 crore post money",
        "runway": "11 months",
        "founders": [
            ("Anjali Warrier", "Co-founder and CEO",
             "Eight years in packaged foods, last running the south India business for a spices "
             "brand. MBA, IIM Kozhikode."),
            ("Deepak Nair", "Co-founder and Head of Operations",
             "Food processing engineer. Set up two fruit pulping lines before this. "
             "B.Tech Food Technology, KAU."),
            ("Farhan Ali", "Head of Sourcing",
             "Twelve years buying coconut, jackfruit and banana across Thrissur and Palakkad."),
        ],
        "metrics": [
            ("Monthly revenue, July 2026", "Rs 78 lakh"),
            ("Modern trade share", "62 percent, direct to consumer 38 percent"),
            ("Retail doors live", "410 across Kerala, Bengaluru and Chennai"),
            ("Direct to consumer repeat rate", "47 percent within 60 days"),
            ("Gross margin", "38 percent"),
            ("Farmers under direct contract", "620, principally Thrissur and Palakkad"),
            ("Plant utilisation", "64 percent of a single shift"),
            ("Monthly burn", "Rs 13.8 lakh"),
        ],
        "traction_rows": [
            ["Month", "Revenue (Rs lakh)", "Doors", "D2C orders", "Gross margin %"],
            ["Feb 2026", "34", "180", "2,140", "31"],
            ["Mar 2026", "41", "216", "2,680", "33"],
            ["Apr 2026", "52", "268", "3,410", "34"],
            ["May 2026", "61", "312", "4,020", "36"],
            ["Jun 2026", "70", "366", "4,780", "37"],
            ["Jul 2026", "78", "410", "5,340", "38"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Anjali Warrier", "Equity", "3,40,000", "34.0"],
            ["Deepak Nair", "Equity", "2,80,000", "28.0"],
            ["Farhan Ali", "Equity", "80,000", "8.0"],
            ["Angel round, Dec 2025 (5 investors)", "CCPS", "1,50,000", "15.0"],
            ["Kerala Startup Mission (grant conversion)", "CCPS", "50,000", "5.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Channel", "Accounts", "Region", "Live since", "Monthly value (Rs)", "Terms"],
            ["Lulu Hypermarket", "9 stores", "Kerala", "Apr 2025", "11,20,000", "45 days"],
            ["Nesto Hypermarket", "14 stores", "Kerala", "Jun 2025", "9,80,000", "45 days"],
            ["Reliance Smart", "38 stores", "Kerala and Karnataka", "Nov 2025", "13,40,000", "60 days"],
            ["More Retail", "26 stores", "Bengaluru", "Feb 2026", "7,60,000", "45 days"],
            ["Quick commerce, two platforms", "Dark stores", "Kochi and Bengaluru", "Mar 2026",
             "6,20,000", "30 days"],
            ["Own website and app", "Direct", "Pan India", "Feb 2024", "29,80,000", "Prepaid"],
        ],
        "unit_rows": [
            ["SKU", "MRP (Rs)", "Net realisation (Rs)", "Material (Rs)", "Contribution (Rs)"],
            ["Tender coconut water, 200 ml", "45", "31", "17", "9.20"],
            ["Jackfruit chips, 100 g", "80", "56", "29", "18.40"],
            ["Banana flour, 500 g", "240", "168", "94", "52.60"],
            ["Coconut milk, 200 ml", "60", "42", "24", "12.10"],
            ["Frozen jackfruit, 400 g", "180", "126", "71", "38.20"],
            ["Curry cut vegetables, 400 g", "70", "49", "31", "10.80"],
        ],
        "risks": [
            "Modern trade pays in 45 to 60 days while farmers are paid in 7, so growth eats working capital.",
            "Jackfruit and tender coconut are seasonal and Q2 is structurally the weakest quarter.",
            "The plant is a single site. A shutdown of even ten days would break modern trade fill rates.",
        ],
        "docs_note": "Sent to investors, July 2026.",
    },
]

ALL_PROFILES = PROFILES + NEW_PROFILES

BY_SLUG = {p["slug"]: p for p in ALL_PROFILES}
BY_NAME = {p["name"]: p for p in ALL_PROFILES}
