# -*- coding: utf-8 -*-
"""
Company profiles for the five demo data rooms on venturethrust@gmail.com.

Everything here is invented. Every generated document carries a SAMPLE
footer so it can never be mistaken for a real company filing.
"""

PROFILES = [
    {
        "slug": "nellara-agrichain",
        "name": "Nellara AgriChain",
        "legal": "Nellara AgriChain Private Limited",
        "cin": "U01100KL2024PTC084912",
        "city": "Kozhikode, Kerala",
        "founded": "March 2024",
        "sector": "Agri supply chain",
        "one_line": "Farm to retail supply chain for Kerala produce.",
        "stage": "Seed",
        "ask": "Rs 6.0 crore",
        "post": "Rs 30 crore post money",
        "runway": "14 months",
        "founders": [
            ("Nithin Raveendran", "Co-founder and CEO",
             "Seven years at a national agri marketplace running the Kerala and coastal Karnataka "
             "category. Built the buyer side from 300 to 4,100 retailers. B.Tech, NIT Calicut."),
            ("Fahad Musthafa", "Co-founder and COO",
             "Third generation produce trader at Palayam market. Runs procurement across 34 farmer "
             "collectives in Wayanad and Malappuram. B.Com, Farook College."),
            ("Reshma Pillai", "Head of Cold Chain",
             "Nine years in temperature controlled logistics, last as regional operations lead for a "
             "listed cold chain operator. M.Tech in Food Process Engineering, TNAU."),
        ],
        "metrics": [
            ("Monthly GMV, July 2026", "Rs 1.42 crore"),
            ("Wastage rate", "7.4 percent, down from 22.1 percent"),
            ("Gross margin", "21.3 percent, up from 8.0 percent"),
            ("Retail accounts live", "61"),
            ("Hotel and restaurant accounts", "9 groups, 38 outlets"),
            ("Farmers supplying", "1,240 across 34 collectives"),
            ("Repeat order rate", "84 percent"),
            ("Monthly burn", "Rs 11.4 lakh"),
        ],
        "traction_rows": [
            ["Month", "GMV (Rs lakh)", "Gross margin %", "Wastage %", "Active buyers"],
            ["Feb 2026", "78", "9.1", "19.6", "34"],
            ["Mar 2026", "86", "11.4", "17.2", "39"],
            ["Apr 2026", "97", "14.0", "14.1", "44"],
            ["May 2026", "112", "16.8", "11.3", "51"],
            ["Jun 2026", "128", "19.2", "9.0", "57"],
            ["Jul 2026", "142", "21.3", "7.4", "61"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Nithin Raveendran", "Equity", "3,10,000", "31.0"],
            ["Fahad Musthafa", "Equity", "2,90,000", "29.0"],
            ["Reshma Pillai", "Equity", "1,00,000", "10.0"],
            ["Kerala Startup Mission (grant conversion)", "CCPS", "60,000", "6.0"],
            ["Angel round, Nov 2025 (7 investors)", "CCPS", "1,40,000", "14.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Account", "Type", "City", "Live since", "Monthly value (Rs)", "Payment terms"],
            ["Grand Hyatt Bolgatty", "Hotel", "Kochi", "Jan 2026", "4,10,000", "30 days"],
            ["Malabar Palace Group", "Hotel", "Kozhikode", "Nov 2025", "3,60,000", "30 days"],
            ["Paragon Restaurants", "Restaurant", "Kozhikode", "Dec 2025", "2,80,000", "21 days"],
            ["Nesto Hypermarket", "Retail", "Kochi", "Feb 2026", "6,20,000", "45 days"],
            ["Lulu Convenience", "Retail", "Kozhikode", "Apr 2026", "5,40,000", "45 days"],
            ["Kalyan Supermarkets", "Retail", "Thrissur", "Mar 2026", "3,10,000", "30 days"],
            ["Zam Zam Family Restaurant", "Restaurant", "Malappuram", "May 2026", "1,20,000", "14 days"],
            ["Fresh Point (12 kirana outlets)", "Retail", "Kozhikode", "Jun 2026", "2,40,000", "7 days"],
        ],
        "unit_rows": [
            ["SKU", "Buy price/kg", "Sell price/kg", "Wastage %", "Logistics/kg", "Contribution/kg"],
            ["Banana, Nendran", "38", "52", "5.2", "3.10", "8.02"],
            ["Tomato", "22", "34", "11.4", "3.10", "6.39"],
            ["Green chilli", "48", "72", "8.8", "3.40", "16.26"],
            ["Ginger", "62", "88", "3.1", "2.90", "20.37"],
            ["Cabbage", "18", "27", "9.6", "3.10", "3.31"],
            ["Curry leaf", "56", "92", "12.0", "3.60", "21.36"],
            ["Coconut", "26", "36", "1.8", "2.40", "7.13"],
        ],
        "risks": [
            "Produce prices swing week to week. We hold no inventory beyond 36 hours and reprice daily.",
            "Cold chain is our largest fixed cost. Two of the four vehicles are on lease, not owned.",
            "Buyer concentration: the top five accounts are 46 percent of GMV.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "zylo-health",
        "name": "Zylo Health",
        "legal": "Zylo Health Technologies Private Limited",
        "cin": "U72900KL2023PTC079344",
        "city": "Kochi, Kerala",
        "founded": "August 2023",
        "sector": "Medical imaging AI",
        "one_line": "AI assisted radiology triage for tier 2 and tier 3 hospitals.",
        "stage": "Seed",
        "ask": "Rs 8.0 crore",
        "post": "Rs 44 crore post money",
        "runway": "11 months",
        "founders": [
            ("Dr Ann Mary Varghese", "Co-founder and CEO",
             "Consultant radiologist for eleven years, last at a 750 bed teaching hospital. Read over "
             "90,000 studies. MD Radiodiagnosis, Amrita Institute of Medical Sciences."),
            ("Sreejith Nair", "Co-founder and CTO",
             "Six years building imaging models at a Mumbai medical AI company, including two products "
             "that cleared CDSCO. M.Tech Computer Vision, IIT Madras."),
            ("Dr Vivek Menon", "Head of Clinical Affairs",
             "Regulatory and clinical validation lead. Ran two prospective device studies to CDSCO "
             "submission. MBBS, DNB, plus a regulatory affairs certification."),
        ],
        "metrics": [
            ("Scans processed, July 2026", "46,200"),
            ("Hospitals live", "11, across Kerala and Tamil Nadu"),
            ("Contracted ARR", "Rs 1.87 crore"),
            ("Realised price per scan", "Rs 34"),
            ("Median time to flag a critical study", "48 seconds"),
            ("Sensitivity on internal validation set", "94.1 percent"),
            ("CDSCO Class B status", "Filed 14 April 2026, under review"),
            ("Monthly burn", "Rs 19.8 lakh"),
        ],
        "traction_rows": [
            ["Month", "Scans", "Hospitals", "Revenue (Rs lakh)", "Critical flags"],
            ["Feb 2026", "21,400", "6", "7.3", "412"],
            ["Mar 2026", "26,800", "7", "9.1", "533"],
            ["Apr 2026", "31,900", "8", "10.8", "611"],
            ["May 2026", "37,600", "9", "12.8", "742"],
            ["Jun 2026", "42,100", "10", "14.3", "816"],
            ["Jul 2026", "46,200", "11", "15.7", "889"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Dr Ann Mary Varghese", "Equity", "3,40,000", "34.0"],
            ["Sreejith Nair", "Equity", "2,60,000", "26.0"],
            ["Dr Vivek Menon", "Equity", "80,000", "8.0"],
            ["Pre seed, Feb 2025 (2 angels)", "CCPS", "1,20,000", "12.0"],
            ["Amrita TBI (grant conversion)", "CCPS", "50,000", "5.0"],
            ["ESOP pool (reserved)", "Options", "1,50,000", "15.0"],
        ],
        "customers": [
            ["Hospital", "Beds", "State", "Live since", "Scans/month", "Contract value (Rs/yr)"],
            ["Sunrise Hospital, Kakkanad", "180", "Kerala", "Nov 2025", "6,200", "25,29,600"],
            ["Lakeshore Extension, Maradu", "120", "Kerala", "Dec 2025", "4,800", "19,58,400"],
            ["MIMS Kottakkal", "210", "Kerala", "Jan 2026", "7,100", "28,96,800"],
            ["KMCT Medical, Kozhikode", "300", "Kerala", "Feb 2026", "8,400", "34,27,200"],
            ["Sree Uthradom, Trivandrum", "140", "Kerala", "Mar 2026", "3,900", "15,91,200"],
            ["Kauvery Hospital, Salem", "160", "Tamil Nadu", "Apr 2026", "4,600", "18,76,800"],
            ["Vijaya Medical, Erode", "90", "Tamil Nadu", "Jun 2026", "2,700", "11,01,600"],
            ["Four district hospitals (pilot)", "-", "Kerala", "Jul 2026", "8,500", "Pilot, unbilled"],
        ],
        "unit_rows": [
            ["Line item", "Per scan (Rs)", "Notes"],
            ["Price realised", "34.00", "Blended across annual contracts"],
            ["GPU inference cost", "2.40", "Batched, spot capacity"],
            ["Storage and transfer", "0.90", "90 day retention, then archive"],
            ["Radiologist audit sampling", "3.10", "8 percent of studies re read"],
            ["Support and account management", "1.80", "Allocated"],
            ["Gross contribution", "25.80", "75.9 percent gross margin"],
        ],
        "risks": [
            "CDSCO Class B clearance is pending. Commercial scale up outside pilots depends on it.",
            "Radiologist trust is earned per hospital. Sales cycle averages 94 days.",
            "Model drift across scanner vendors requires per site calibration in the first 30 days.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "voltaneer",
        "name": "Voltaneer",
        "legal": "Voltaneer Energy Systems Private Limited",
        "cin": "U31900TZ2023PTC039771",
        "city": "Coimbatore, Tamil Nadu",
        "founded": "June 2023",
        "sector": "Industrial IoT and energy",
        "one_line": "Energy monitoring for small and mid sized factories.",
        "stage": "Seed",
        "ask": "Rs 7.0 crore",
        "post": "Rs 38 crore post money",
        "runway": "13 months",
        "founders": [
            ("Karthik Subramanian", "Co-founder and CEO",
             "Twelve years in industrial power electronics, last as India applications head for a "
             "global drives manufacturer. B.E. Electrical, PSG Tech."),
            ("Aravind Rangaswamy", "Co-founder and CTO",
             "Embedded systems and edge analytics. Previously built metering firmware shipped on "
             "40,000 units. M.S. Electrical Engineering, Arizona State."),
            ("Divya Balan", "VP Sales",
             "Nine years selling capital equipment into Coimbatore and Tiruppur clusters. Carried and "
             "exceeded a Rs 12 crore annual quota. MBA, Bharathiar University."),
        ],
        "metrics": [
            ("ARR, July 2026", "Rs 2.34 crore"),
            ("Recurring share of revenue", "47 percent, up from 24 percent"),
            ("Median sales cycle", "71 days, down from 264 days"),
            ("Factories monitored", "88"),
            ("Average verified saving per factory", "8.4 percent of the power bill"),
            ("Net revenue retention", "118 percent"),
            ("Logo churn, trailing 12 months", "6 percent"),
            ("Monthly burn", "Rs 16.2 lakh"),
        ],
        "traction_rows": [
            ["Month", "ARR (Rs lakh)", "Factories", "Recurring %", "Median cycle (days)"],
            ["Feb 2026", "142", "58", "27", "212"],
            ["Mar 2026", "158", "63", "31", "186"],
            ["Apr 2026", "176", "69", "36", "148"],
            ["May 2026", "197", "76", "40", "112"],
            ["Jun 2026", "216", "82", "44", "88"],
            ["Jul 2026", "234", "88", "47", "71"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Karthik Subramanian", "Equity", "3,20,000", "32.0"],
            ["Aravind Rangaswamy", "Equity", "2,80,000", "28.0"],
            ["Divya Balan", "Equity", "70,000", "7.0"],
            ["Angel round, Mar 2025 (5 investors)", "CCPS", "1,60,000", "16.0"],
            ["Strategic angel, distribution partner", "CCPS", "50,000", "5.0"],
            ["ESOP pool (reserved)", "Options", "1,20,000", "12.0"],
        ],
        "customers": [
            ["Factory", "Sector", "Cluster", "Live since", "Annual subscription (Rs)", "Verified saving"],
            ["Sri Kumaran Textiles", "Spinning", "Tiruppur", "Sep 2025", "3,60,000", "9.1 percent"],
            ["Precision Castings Ltd", "Foundry", "Coimbatore", "Oct 2025", "4,20,000", "11.4 percent"],
            ["Anand Pumps", "Pumps", "Coimbatore", "Nov 2025", "3,00,000", "7.2 percent"],
            ["Vetri Knits", "Knitwear", "Tiruppur", "Jan 2026", "2,40,000", "8.8 percent"],
            ["Sakthi Auto Components", "Auto parts", "Erode", "Feb 2026", "4,80,000", "6.9 percent"],
            ["Nachimuthu Mills", "Spinning", "Pollachi", "Mar 2026", "3,60,000", "10.2 percent"],
            ["KG Denim (unit 2)", "Textiles", "Coimbatore", "May 2026", "5,40,000", "7.8 percent"],
            ["Suguna Feeds, plant 4", "Food processing", "Udumalpet", "Jun 2026", "4,20,000", "8.0 percent"],
        ],
        "unit_rows": [
            ["Line item", "Per factory, year 1 (Rs)", "Per factory, year 2 (Rs)"],
            ["Software subscription", "2,40,000", "2,64,000"],
            ["Sensor hardware (one time)", "1,10,000", "0"],
            ["Installation and commissioning", "35,000", "0"],
            ["Hardware cost of goods", "-62,000", "0"],
            ["Install labour", "-21,000", "0"],
            ["Cloud and connectivity", "-18,000", "-19,000"],
            ["Support", "-24,000", "-24,000"],
            ["Contribution", "2,60,000", "2,21,000"],
        ],
        "risks": [
            "Hardware still gates every new deployment and carries a 9 week lead time on two components.",
            "Capex approval remains the slowest step at factories above 200 employees.",
            "Savings claims are audited by the customer's own meter. One disputed claim can stall a cluster.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "aegis-drone-systems",
        "name": "Aegis Drone Systems",
        "legal": "Aegis Drone Systems Private Limited",
        "cin": "U74999KL2024PTC086220",
        "city": "Kochi, Kerala",
        "founded": "January 2024",
        "sector": "Industrial inspection",
        "one_line": "Drone inspection for ports, transmission lines and plantation estates.",
        "stage": "Seed",
        "ask": "Rs 5.5 crore",
        "post": "Rs 26 crore post money",
        "runway": "9 months",
        "founders": [
            ("Rohan Fernandes", "Co-founder and CEO",
             "Five years at a Bengaluru drone services company, last running the industrial inspection "
             "vertical across four states. B.E. Aeronautical, MIT Manipal."),
            ("Capt. Ismail Haq", "Co-founder and Chief Pilot",
             "Eighteen years flying with the Indian Air Force, then civil UAS instructor. DGCA "
             "certified remote pilot instructor, 1,900 logged UAS hours."),
            ("Meera Nambiar", "Head of Analytics",
             "Computer vision for defect detection. Previously built rail track inspection models for "
             "a public sector client. M.Tech, CUSAT."),
        ],
        "metrics": [
            ("Revenue, FY26", "Rs 1.10 crore"),
            ("Inspection cycles delivered", "46"),
            ("Sites under annual retainer", "0 signed, 3 in negotiation"),
            ("Repeat customers", "2 of 14"),
            ("Average project value", "Rs 2.39 lakh"),
            ("Defect detection precision, internal set", "88.6 percent"),
            ("DGCA BVLOS status", "Applied 2 March 2026, pending"),
            ("Monthly burn", "Rs 9.6 lakh"),
        ],
        "traction_rows": [
            ["Quarter", "Projects", "Revenue (Rs lakh)", "Repeat %", "Retainers signed"],
            ["Q1 FY26", "6", "13", "0", "0"],
            ["Q2 FY26", "9", "21", "11", "0"],
            ["Q3 FY26", "13", "31", "15", "0"],
            ["Q4 FY26", "18", "45", "17", "0"],
            ["Q1 FY27", "11", "28", "18", "0"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Rohan Fernandes", "Equity", "3,60,000", "36.0"],
            ["Capt. Ismail Haq", "Equity", "2,80,000", "28.0"],
            ["Meera Nambiar", "Equity", "1,10,000", "11.0"],
            ["Friends and family, Jun 2025", "CCPS", "90,000", "9.0"],
            ["Kerala Startup Mission (grant conversion)", "CCPS", "60,000", "6.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Client", "Asset type", "Location", "Engagement", "Value (Rs)", "Repeat"],
            ["Cochin Port Authority", "Wharf and cranes", "Kochi", "Mar 2026", "6,40,000", "Yes"],
            ["KSEB transmission circle", "132 kV lines", "Thrissur", "Feb 2026", "4,10,000", "No"],
            ["Harrisons Malayalam", "Tea estate survey", "Idukki", "Apr 2026", "2,80,000", "Yes"],
            ["Adani Vizhinjam (vendor trial)", "Breakwater", "Trivandrum", "May 2026", "3,20,000", "No"],
            ["AVT Plantations", "Rubber estate", "Kottayam", "Jan 2026", "1,90,000", "No"],
            ["Kerala Water Authority", "Overhead tanks", "Kochi", "Jun 2026", "1,40,000", "No"],
            ["BPCL Kochi Refinery (trial)", "Flare stack", "Kochi", "Jul 2026", "2,60,000", "No"],
        ],
        "unit_rows": [
            ["Line item", "Per inspection cycle (Rs)", "Notes"],
            ["Project fee", "2,39,000", "Average across 46 cycles"],
            ["Crew, two people, three days", "-46,000", "Pilot plus spotter"],
            ["Travel and site access", "-21,000", "Includes permits"],
            ["Equipment depreciation", "-28,000", "Airframe and payload"],
            ["Insurance", "-9,000", "Per sortie rider"],
            ["Analytics and reporting", "-34,000", "Two analyst days"],
            ["Contribution", "1,01,000", "42.3 percent"],
        ],
        "risks": [
            "Revenue is project based. Nothing recurs until a retainer is signed.",
            "BVLOS clearance gates the transmission line business, which is the largest pipeline.",
            "One airframe loss would remove roughly a third of current flying capacity.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
    {
        "slug": "kadal-systems",
        "name": "Kadal Systems",
        "legal": "Kadal Systems Private Limited",
        "cin": "U31909KL2023PTC081455",
        "city": "Kollam, Kerala",
        "founded": "May 2023",
        "sector": "Marine safety IoT",
        "one_line": "Satellite messaging and distress alerts for small fishing vessels.",
        "stage": "Seed",
        "ask": "Rs 4.5 crore",
        "post": "Rs 22 crore post money",
        "runway": "10 months",
        "founders": [
            ("Sujith Kumar", "Co-founder and CEO",
             "Marine engineer, eight years at sea and four building vessel electronics. Grew up in a "
             "fishing family in Neendakara. B.Tech Marine Engineering, CUSAT."),
            ("Anas Rahman", "Co-founder and CTO",
             "RF and satellite communications. Previously designed terminals for a maritime tracking "
             "provider. M.Tech Communication Systems, NIT Calicut."),
            ("Lakshmi Menon", "Head of Field Operations",
             "Ran a state fisheries extension programme across three districts. Knows every harbour "
             "society officer from Kollam to Alappuzha. MSW, Loyola Trivandrum."),
        ],
        "metrics": [
            ("Units deployed", "3,100"),
            ("Units bought at full price, no subsidy", "240"),
            ("Units under state subsidy scheme", "2,860"),
            ("Annual connectivity subscription", "Rs 1,800 per vessel"),
            ("Subscription renewal rate, year 2", "71 percent"),
            ("Distress alerts relayed", "37, including 9 rescues"),
            ("Hardware gross margin", "31 percent"),
            ("Monthly burn", "Rs 8.1 lakh"),
        ],
        "traction_rows": [
            ["Quarter", "Units shipped", "Full price units", "Subscription base", "Revenue (Rs lakh)"],
            ["Q1 FY26", "410", "12", "980", "31"],
            ["Q2 FY26", "620", "28", "1,540", "44"],
            ["Q3 FY26", "740", "51", "2,180", "56"],
            ["Q4 FY26", "880", "84", "2,760", "68"],
            ["Q1 FY27", "450", "65", "3,100", "39"],
        ],
        "cap": [
            ["Holder", "Instrument", "Shares", "Fully diluted %"],
            ["Sujith Kumar", "Equity", "3,50,000", "35.0"],
            ["Anas Rahman", "Equity", "3,00,000", "30.0"],
            ["Lakshmi Menon", "Equity", "90,000", "9.0"],
            ["Angel round, Aug 2025 (4 investors)", "CCPS", "1,10,000", "11.0"],
            ["Maritime India grant (conversion)", "CCPS", "50,000", "5.0"],
            ["ESOP pool (reserved)", "Options", "1,00,000", "10.0"],
        ],
        "customers": [
            ["Channel", "District", "Units", "Subsidy", "Full price", "Renewals due FY27"],
            ["Neendakara harbour society", "Kollam", "820", "760", "60", "640"],
            ["Sakthikulangara society", "Kollam", "540", "500", "40", "410"],
            ["Munambam boat owners", "Ernakulam", "610", "560", "50", "470"],
            ["Beypore association", "Kozhikode", "430", "400", "30", "300"],
            ["Vizhinjam society", "Trivandrum", "380", "350", "30", "260"],
            ["Direct sales, boat owners", "Multiple", "240", "0", "240", "180"],
            ["Ponnani society (pilot)", "Malappuram", "80", "290", "0", "0"],
        ],
        "unit_rows": [
            ["Line item", "Per unit (Rs)", "Notes"],
            ["Device price, full", "14,500", "Subsidised price to owner is Rs 3,600"],
            ["Bill of materials", "-8,200", "Terminal, antenna, enclosure"],
            ["Assembly and testing", "-1,100", "In house, Kollam"],
            ["Installation on vessel", "-900", "Field team"],
            ["Warranty provision", "-800", "24 months"],
            ["Hardware contribution", "3,500", "24.1 percent"],
            ["Annual connectivity subscription", "1,800", "Airtime cost Rs 640, margin 64 percent"],
        ],
        "risks": [
            "Almost all demand to date came through a state subsidy scheme with an annual budget cycle.",
            "Satellite airtime is bought from a single provider on a one year contract.",
            "Monsoon months, June to August, are close to zero for new installations.",
        ],
        "docs_note": "Prepared for investor diligence, July 2026.",
    },
]

BY_SLUG = {p["slug"]: p for p in PROFILES}
BY_NAME = {p["name"]: p for p in PROFILES}
