-- ============================================================================
-- DEMO INVESTOR ACCOUNT  ·  venturethrust@gmail.com
-- ============================================================================
-- Investor : venturethrust@gmail.com
-- Owner    : omprakash@venturethrust.com  (owns the five data rooms, so they
--            legitimately appear under Shared with me for the investor)
--
-- Generated by scripts/demo_docs/build.py. Every file row below has a real
-- object already uploaded to the vdr-files bucket at the same storage_path,
-- so opening any document works.
--
-- Safe to re-run. It removes only the investor's own rows and the five demo
-- spaces, never anything else.
-- ============================================================================

alter table public.profiles
  add column if not exists signup_notified boolean not null default false;
update public.profiles set signup_notified = true where signup_notified = false;

alter table public.dw_watchlist
  add column if not exists note text,
  add column if not exists quarterly_report boolean not null default false;

do $$
declare
  v_inv uuid;
  v_own uuid;
  v_mgr uuid;
  s_id  uuid;
  rec   record;
  ids   uuid[] := '{}';
  demo_names text[] := array['Nellara AgriChain', 'Zylo Health', 'Voltaneer', 'Aegis Drone Systems', 'Kadal Systems'];
begin
  select id into v_inv from auth.users where lower(email) = 'venturethrust@gmail.com';
  if v_inv is null then
    raise exception 'No auth user for venturethrust@gmail.com. Sign up with that email first.';
  end if;
  select id into v_own from auth.users where lower(email) = 'omprakash@venturethrust.com';
  if v_own is null then v_own := v_inv; end if;
  select id into v_mgr from public.profiles where lower(email) = 'omprakash@venturethrust.com';

  -- ── Wipe ─────────────────────────────────────────────────────────────────
  select coalesce(array_agg(id), '{}') into ids from public.spaces
   where name = any(demo_names) and created_by in (v_inv, v_own);

  -- Anything ever addressed to this inbox by ANY sender is cleared too.
  -- Old test sends from other accounts are what put stray PDFs and videos
  -- in Shared with me, and they are not owned by v_inv or v_own.
  if to_regclass('public.share_link_access_logs') is not null then
    delete from public.share_link_access_logs where share_link_id in (
      select id from public.share_links
       where space_id = any(ids)
          or lower(recipient_email) = 'venturethrust@gmail.com'
          or space_id in (select id from public.spaces where created_by = v_inv));
  end if;
  if to_regclass('public.viewer_sessions') is not null then
    delete from public.viewer_sessions where space_id = any(ids);
  end if;
  if to_regclass('public.share_links') is not null then
    delete from public.share_links where space_id = any(ids)
      or lower(recipient_email) = 'venturethrust@gmail.com'
      or space_id in (select id from public.spaces where created_by = v_inv);
  end if;
  if to_regclass('public.visits') is not null then
    delete from public.visits where space_id = any(ids)
      or space_id in (select id from public.spaces where created_by = v_inv);
  end if;
  if to_regclass('public.files') is not null then
    delete from public.files where space_id = any(ids) or user_id = v_inv;
  end if;
  if to_regclass('public.folders') is not null then
    delete from public.folders where space_id = any(ids) or user_id = v_inv;
  end if;
  if to_regclass('public.spaces') is not null then
    delete from public.spaces where id = any(ids) or created_by = v_inv;
  end if;
  if to_regclass('public.dw_update_events') is not null then
    delete from public.dw_update_events where founder_id in (v_inv, v_own);
  end if;
  if to_regclass('public.dw_watchlist') is not null then
    delete from public.dw_watchlist where investor_id = v_inv;
  end if;
  if to_regclass('public.alerts') is not null then
    delete from public.alerts where user_id = v_inv;
  end if;
  if to_regclass('public.dw_offers') is not null then
    delete from public.dw_offers where lower(investor_email) = 'venturethrust@gmail.com';
  end if;

  -- ── Investor plan on ─────────────────────────────────────────────────────
  update public.profiles
     set is_investor = true, plan = 'vdr_ai', plan_status = 'active',
         plan_expires_at = now() + interval '365 days',
         dw_auto_assign = true, signup_notified = true
   where id = v_inv;

  -- ── Five data rooms, their share link, invite and watchlist row ─────────
  for rec in
    select * from (values
      ('Nellara AgriChain',
       'Farm to retail supply chain for Kerala produce. Based in Kozhikode, Kerala.',
       'Passed at pre seed, March 2026. Right problem, wrong economics: 22 percent wastage and 8 percent gross margin meant every rupee of growth was losing money. The Kerala produce gap is real and the founder knows the Wayanad collectives personally. Come back when wastage is under 10 percent and gross margin is above 18 percent.',
       false, true, timestamptz '2026-03-12 10:40:00+05:30'),
      ('Zylo Health',
       'AI assisted radiology triage for tier 2 and tier 3 hospitals. Based in Kochi, Kerala.',
       'Strong clinical team out of Amrita and the radiologist shortage in tier 2 hospitals is real. But everything depends on CDSCO Class B clearance, which they had not even filed when we met. No point pricing a regulated device before the regulator speaks. Revisit on clearance plus one paying hospital outside Kerala.',
       true, true, timestamptz '2026-02-02 16:05:00+05:30'),
      ('Voltaneer',
       'Energy monitoring for small and mid sized factories. Based in Coimbatore, Tamil Nadu.',
       'A hardware business wearing a software badge. 76 percent of revenue was one time sensor sales and the average deal took nearly nine months because it needed a capex approval. The energy saving is real, the business model was not. Come back when recurring software is above 40 percent of revenue and the sales cycle is under 90 days.',
       false, true, timestamptz '2026-02-05 12:15:00+05:30'),
      ('Aegis Drone Systems',
       'Drone inspection for ports, transmission lines and plantation estates. Based in Kochi, Kerala.',
       'Good pilots, good imagery, no repeat business. Every rupee so far has come from one off inspections, and DGCA BVLOS permissions were still pending when we met. Inspection only becomes a business when it becomes a retainer. Revisit when at least three sites are on annual contracts and BVLOS clearance is granted.',
       false, true, timestamptz '2026-04-18 15:25:00+05:30'),
      ('Kadal Systems',
       'Satellite messaging and distress alerts for small fishing vessels. Based in Kollam, Kerala.',
       'Genuinely important product and the safety case is unarguable. My problem is who pays. Almost all current units were bought through a state subsidy scheme, so I have no evidence a boat owner pays full price from his own pocket. Show me 200 units sold without subsidy and I will look again.',
       false, false, timestamptz '2026-05-06 11:05:00+05:30')
    ) as t(nm, descr, note, quarterly, opened, added)
  loop
    s_id := gen_random_uuid();

    insert into public.spaces (id, name, title, description, created_by)
    values (s_id, rec.nm, rec.nm, rec.descr, v_own);

    -- Five top level diligence folders. No wrapper folder: the investor
    -- should land on the structure, not one folder called Root.
    insert into public.folders (id, user_id, name, space_id, parent_id, position)
    select gen_random_uuid(), v_own, fol, s_id, null, ord
      from unnest(array['01 Company Overview', '02 Financials', '03 Product and Technology', '04 Customers and Traction', '05 Legal and Compliance']) with ordinality as u(fol, ord);

    insert into public.share_links
      (id, space_id, token, is_active, email_required, recipient_email, created_by, created_at)
    values (gen_random_uuid(), s_id, encode(gen_random_bytes(16), 'hex'), true, true,
            'venturethrust@gmail.com', v_own, rec.added);

    insert into public.alerts (user_id, space_id, type, message, created_at, read_at)
    values (v_inv, s_id, 'space_shared',
            rec.nm || ' shared their data room with you.',
            rec.added, case when rec.opened then rec.added + interval '2 hours' else null end);

    insert into public.dw_watchlist
      (id, investor_id, founder_id, space_id, file_id, startup_name, manager_id, note,
       quarterly_report, created_at)
    values (gen_random_uuid(), v_inv, v_own, s_id, null, rec.nm, v_mgr,
            rec.note, rec.quarterly, rec.added);
  end loop;

  -- ── 75 documents, each already uploaded to the vdr-files bucket ────────
  insert into public.files
    (id, user_id, folder_id, space_id, name, type, storage_path,
     size_bytes, views, position, created_at)
  select gen_random_uuid()::text, v_own, fo.id, sp.id, t.fname, t.ftype,
         t.spath, t.sz, t.vws, t.pos, now() - (t.age || ' days')::interval
    from (values
      ('Nellara AgriChain','01 Company Overview','Nellara Pitch Deck v5.pdf','Deck','demo/nellara-agrichain/Nellara Pitch Deck v5.pdf',11589,0,1,3),
      ('Nellara AgriChain','01 Company Overview','One Pager.pdf','PDF','demo/nellara-agrichain/One Pager.pdf',3462,7,2,8),
      ('Nellara AgriChain','01 Company Overview','Founder Profiles.pdf','PDF','demo/nellara-agrichain/Founder Profiles.pdf',3551,14,3,13),
      ('Nellara AgriChain','01 Company Overview','Board Update Q1 FY27.pdf','PDF','demo/nellara-agrichain/Board Update Q1 FY27.pdf',3359,21,4,18),
      ('Nellara AgriChain','02 Financials','Financial Model FY27.xlsx','Sheet','demo/nellara-agrichain/Financial Model FY27.xlsx',7261,2,1,23),
      ('Nellara AgriChain','02 Financials','Unit Economics by SKU.xlsx','Sheet','demo/nellara-agrichain/Unit Economics by SKU.xlsx',5735,9,2,28),
      ('Nellara AgriChain','02 Financials','Cap Table.xlsx','Sheet','demo/nellara-agrichain/Cap Table.xlsx',5615,16,3,33),
      ('Nellara AgriChain','02 Financials','GST Returns FY26.pdf','PDF','demo/nellara-agrichain/GST Returns FY26.pdf',3365,23,4,38),
      ('Nellara AgriChain','03 Product and Technology','Cold Chain Route Plan.pdf','PDF','demo/nellara-agrichain/Cold Chain Route Plan.pdf',3139,4,1,43),
      ('Nellara AgriChain','03 Product and Technology','Wastage Tracking Method.pdf','PDF','demo/nellara-agrichain/Wastage Tracking Method.pdf',3647,11,2,4),
      ('Nellara AgriChain','03 Product and Technology','Procurement App Overview.pdf','PDF','demo/nellara-agrichain/Procurement App Overview.pdf',3014,18,3,9),
      ('Nellara AgriChain','04 Customers and Traction','Hotel Supply Agreements.pdf','PDF','demo/nellara-agrichain/Hotel Supply Agreements.pdf',3087,25,1,14),
      ('Nellara AgriChain','04 Customers and Traction','Farmer Collective MOUs.pdf','PDF','demo/nellara-agrichain/Farmer Collective MOUs.pdf',3075,6,2,19),
      ('Nellara AgriChain','04 Customers and Traction','Customer List Jul 2026.xlsx','Sheet','demo/nellara-agrichain/Customer List Jul 2026.xlsx',5839,13,3,24),
      ('Nellara AgriChain','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF','demo/nellara-agrichain/Certificate of Incorporation.pdf',3370,20,1,29),
      ('Nellara AgriChain','05 Legal and Compliance','FSSAI License.pdf','PDF','demo/nellara-agrichain/FSSAI License.pdf',2836,1,2,34),
      ('Nellara AgriChain','05 Legal and Compliance','Shareholder Agreement.pdf','PDF','demo/nellara-agrichain/Shareholder Agreement.pdf',2976,8,3,39),
      ('Zylo Health','01 Company Overview','Zylo Pitch Deck.pdf','Deck','demo/zylo-health/Zylo Pitch Deck.pdf',11552,15,1,44),
      ('Zylo Health','01 Company Overview','Clinical One Pager.pdf','PDF','demo/zylo-health/Clinical One Pager.pdf',3676,22,2,5),
      ('Zylo Health','01 Company Overview','Founding Team.pdf','PDF','demo/zylo-health/Founding Team.pdf',3512,3,3,10),
      ('Zylo Health','02 Financials','Financial Model.xlsx','Sheet','demo/zylo-health/Financial Model.xlsx',7287,10,1,15),
      ('Zylo Health','02 Financials','Per Scan Unit Economics.xlsx','Sheet','demo/zylo-health/Per Scan Unit Economics.xlsx',5636,17,2,20),
      ('Zylo Health','02 Financials','Cap Table.xlsx','Sheet','demo/zylo-health/Cap Table.xlsx',5606,24,3,25),
      ('Zylo Health','03 Product and Technology','Triage Algorithm Overview.pdf','PDF','demo/zylo-health/Triage Algorithm Overview.pdf',3143,5,1,30),
      ('Zylo Health','03 Product and Technology','Clinical Validation Summary.pdf','PDF','demo/zylo-health/Clinical Validation Summary.pdf',3721,12,2,35),
      ('Zylo Health','03 Product and Technology','Product Overview.pdf','PDF','demo/zylo-health/Product Overview.pdf',2872,19,3,40),
      ('Zylo Health','04 Customers and Traction','Hospital Contracts.pdf','PDF','demo/zylo-health/Hospital Contracts.pdf',3622,0,1,45),
      ('Zylo Health','04 Customers and Traction','Scan Volume Report Jul 2026.xlsx','Sheet','demo/zylo-health/Scan Volume Report Jul 2026.xlsx',5880,7,2,6),
      ('Zylo Health','04 Customers and Traction','Radiologist Coverage Study.pdf','PDF','demo/zylo-health/Radiologist Coverage Study.pdf',2989,14,3,11),
      ('Zylo Health','05 Legal and Compliance','CDSCO Filing Acknowledgement.pdf','PDF','demo/zylo-health/CDSCO Filing Acknowledgement.pdf',3122,21,1,16),
      ('Zylo Health','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF','demo/zylo-health/Certificate of Incorporation.pdf',3365,2,2,21),
      ('Zylo Health','05 Legal and Compliance','Data Protection Policy.pdf','PDF','demo/zylo-health/Data Protection Policy.pdf',3096,9,3,26),
      ('Voltaneer','01 Company Overview','Voltaneer Pitch Deck v3.pdf','Deck','demo/voltaneer/Voltaneer Pitch Deck v3.pdf',11613,16,1,31),
      ('Voltaneer','01 Company Overview','One Pager.pdf','PDF','demo/voltaneer/One Pager.pdf',3534,23,2,36),
      ('Voltaneer','01 Company Overview','Team and Advisors.pdf','PDF','demo/voltaneer/Team and Advisors.pdf',3507,4,3,41),
      ('Voltaneer','02 Financials','Financial Model.xlsx','Sheet','demo/voltaneer/Financial Model.xlsx',7274,11,1,46),
      ('Voltaneer','02 Financials','ARR Bridge FY27.xlsx','Sheet','demo/voltaneer/ARR Bridge FY27.xlsx',5612,18,2,7),
      ('Voltaneer','02 Financials','Cap Table.xlsx','Sheet','demo/voltaneer/Cap Table.xlsx',5610,25,3,12),
      ('Voltaneer','03 Product and Technology','Sensor Spec Sheet.pdf','PDF','demo/voltaneer/Sensor Spec Sheet.pdf',3508,6,1,17),
      ('Voltaneer','03 Product and Technology','Dashboard Overview.pdf','PDF','demo/voltaneer/Dashboard Overview.pdf',3029,13,2,22),
      ('Voltaneer','03 Product and Technology','Firmware Release Notes.pdf','PDF','demo/voltaneer/Firmware Release Notes.pdf',3082,20,3,27),
      ('Voltaneer','04 Customers and Traction','Annual SaaS Agreement Template.pdf','PDF','demo/voltaneer/Annual SaaS Agreement Template.pdf',3036,1,1,32),
      ('Voltaneer','04 Customers and Traction','Customer Savings Report.xlsx','Sheet','demo/voltaneer/Customer Savings Report.xlsx',5868,8,2,37),
      ('Voltaneer','04 Customers and Traction','Sales Cycle Export Jul 2026.xlsx','Sheet','demo/voltaneer/Sales Cycle Export Jul 2026.xlsx',5969,15,3,42),
      ('Voltaneer','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF','demo/voltaneer/Certificate of Incorporation.pdf',3360,22,1,3),
      ('Voltaneer','05 Legal and Compliance','IP Assignment Deed.pdf','PDF','demo/voltaneer/IP Assignment Deed.pdf',3025,3,2,8),
      ('Voltaneer','05 Legal and Compliance','ESOP Policy.pdf','PDF','demo/voltaneer/ESOP Policy.pdf',3291,10,3,13),
      ('Aegis Drone Systems','01 Company Overview','Aegis Pitch Deck.pdf','Deck','demo/aegis-drone-systems/Aegis Pitch Deck.pdf',11725,17,1,18),
      ('Aegis Drone Systems','01 Company Overview','Capability Statement.pdf','PDF','demo/aegis-drone-systems/Capability Statement.pdf',3120,24,2,23),
      ('Aegis Drone Systems','01 Company Overview','Pilot Team Credentials.pdf','PDF','demo/aegis-drone-systems/Pilot Team Credentials.pdf',3539,5,3,28),
      ('Aegis Drone Systems','02 Financials','Financial Model.xlsx','Sheet','demo/aegis-drone-systems/Financial Model.xlsx',7281,12,1,33),
      ('Aegis Drone Systems','02 Financials','Project Level P and L.xlsx','Sheet','demo/aegis-drone-systems/Project Level P and L.xlsx',5637,19,2,38),
      ('Aegis Drone Systems','02 Financials','Cap Table.xlsx','Sheet','demo/aegis-drone-systems/Cap Table.xlsx',5616,0,3,43),
      ('Aegis Drone Systems','03 Product and Technology','Inspection Platform Overview.pdf','PDF','demo/aegis-drone-systems/Inspection Platform Overview.pdf',3160,7,1,4),
      ('Aegis Drone Systems','03 Product and Technology','Sample Defect Report.pdf','PDF','demo/aegis-drone-systems/Sample Defect Report.pdf',3647,14,2,9),
      ('Aegis Drone Systems','03 Product and Technology','Fleet and Payload Specs.pdf','PDF','demo/aegis-drone-systems/Fleet and Payload Specs.pdf',2940,21,3,14),
      ('Aegis Drone Systems','04 Customers and Traction','Port Authority Work Order.pdf','PDF','demo/aegis-drone-systems/Port Authority Work Order.pdf',2967,2,1,19),
      ('Aegis Drone Systems','04 Customers and Traction','Client List.xlsx','Sheet','demo/aegis-drone-systems/Client List.xlsx',5833,9,2,24),
      ('Aegis Drone Systems','05 Legal and Compliance','DGCA Application Status.pdf','PDF','demo/aegis-drone-systems/DGCA Application Status.pdf',3033,16,1,29),
      ('Aegis Drone Systems','05 Legal and Compliance','Aviation Insurance Certificate.pdf','PDF','demo/aegis-drone-systems/Aviation Insurance Certificate.pdf',2855,23,2,34),
      ('Aegis Drone Systems','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF','demo/aegis-drone-systems/Certificate of Incorporation.pdf',3374,4,3,39),
      ('Kadal Systems','01 Company Overview','Kadal Pitch Deck.pdf','Deck','demo/kadal-systems/Kadal Pitch Deck.pdf',11637,11,1,44),
      ('Kadal Systems','01 Company Overview','Product One Pager.pdf','PDF','demo/kadal-systems/Product One Pager.pdf',3555,18,2,5),
      ('Kadal Systems','01 Company Overview','Founders.pdf','PDF','demo/kadal-systems/Founders.pdf',3502,25,3,10),
      ('Kadal Systems','02 Financials','Financial Model.xlsx','Sheet','demo/kadal-systems/Financial Model.xlsx',7264,6,1,15),
      ('Kadal Systems','02 Financials','Unit Cost Breakdown.xlsx','Sheet','demo/kadal-systems/Unit Cost Breakdown.xlsx',5666,13,2,20),
      ('Kadal Systems','02 Financials','Cap Table.xlsx','Sheet','demo/kadal-systems/Cap Table.xlsx',5602,20,3,25),
      ('Kadal Systems','03 Product and Technology','Device Spec Sheet.pdf','PDF','demo/kadal-systems/Device Spec Sheet.pdf',3656,1,1,30),
      ('Kadal Systems','03 Product and Technology','Satellite Coverage Map.pdf','PDF','demo/kadal-systems/Satellite Coverage Map.pdf',3015,8,2,35),
      ('Kadal Systems','03 Product and Technology','Field Trial Report.pdf','PDF','demo/kadal-systems/Field Trial Report.pdf',3102,15,3,40),
      ('Kadal Systems','04 Customers and Traction','Unit Sales Register Jun 2026.xlsx','Sheet','demo/kadal-systems/Unit Sales Register Jun 2026.xlsx',5778,22,1,45),
      ('Kadal Systems','04 Customers and Traction','Fisheries Dept Subsidy Order.pdf','PDF','demo/kadal-systems/Fisheries Dept Subsidy Order.pdf',3018,3,2,6),
      ('Kadal Systems','05 Legal and Compliance','WPC Equipment License.pdf','PDF','demo/kadal-systems/WPC Equipment License.pdf',2909,10,1,11),
      ('Kadal Systems','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF','demo/kadal-systems/Certificate of Incorporation.pdf',3356,17,2,16),
      ('Kadal Systems','05 Legal and Compliance','Founder Agreement.pdf','PDF','demo/kadal-systems/Founder Agreement.pdf',3032,24,3,21)
    ) as t(sname, fol, fname, ftype, spath, sz, vws, pos, age)
    join public.spaces  sp on sp.name = t.sname and sp.created_by = v_own
    join public.folders fo on fo.space_id = sp.id and fo.name = t.fol;

  -- ── Founder update history behind the briefs ─────────────────────────────
  insert into public.dw_update_events (id, founder_id, space_id, file_id, file_name, event_type, created_at)
  select gen_random_uuid(), v_own, f.space_id, null, f.name, 'file_updated',
         now() - ((row_number() over (order by f.created_at desc)) || ' days')::interval
    from public.files f
    join public.spaces s on s.id = f.space_id
   where s.name = any(demo_names) and s.created_by = v_own
   limit 28;

  -- ── The two priority briefs waiting ──────────────────────────────────────
  insert into public.alerts (user_id, space_id, type, message, created_at)
  select v_inv, id, 'dw_update',
         'Priority brief ready: Nellara AgriChain has crossed both conditions from your note. Wastage 7.4 percent, gross margin 21.3 percent.',
         now() - interval '10 days'
    from public.spaces where name = 'Nellara AgriChain' and created_by = v_own limit 1;

  insert into public.alerts (user_id, space_id, type, message, created_at)
  select v_inv, id, 'dw_update',
         'Priority brief ready: Voltaneer is at 47 percent recurring revenue with a 71 day sales cycle, past both thresholds you set.',
         now() - interval '7 days'
    from public.spaces where name = 'Voltaneer' and created_by = v_own limit 1;
end $$;
