-- ============================================================================
-- DEMO INVESTOR ACCOUNT  ·  venturethrust@gmail.com
-- ============================================================================
-- Investor : venturethrust@gmail.com
-- Owner    : omprakash@venturethrust.com  (owns the five data rooms, so they
--            legitimately appear under Shared with me for the investor)
--
-- Generated by scripts/demo_docs/build.py. Every file row below has a real
-- object already uploaded to the vdr-files bucket at the same storage_path,
-- so opening any document works.
--
-- Safe to re-run. It removes only the investor's own rows and the five demo
-- spaces, never anything else.
-- ============================================================================

alter table public.profiles
  add column if not exists signup_notified boolean not null default false;
update public.profiles set signup_notified = true where signup_notified = false;

alter table public.dw_watchlist
  add column if not exists note text,
  add column if not exists quarterly_report boolean not null default false;

do $$
declare
  v_inv uuid;
  v_own uuid;
  v_mgr uuid;
  s_id  uuid;
  rec   record;
  ids   uuid[] := '{}';
  demo_names text[] := array['Nellara AgriChain', 'Zylo Health', 'Voltaneer', 'Aegis Drone Systems', 'Kadal Systems', 'Anvaya AI', 'Thooval Studios', 'Kalpana Robotics', 'Metricon Interconnect', 'Puzha Foods'];
begin
  select id into v_inv from auth.users where lower(email) = 'venturethrust@gmail.com';
  if v_inv is null then
    raise exception 'No auth user for venturethrust@gmail.com. Sign up with that email first.';
  end if;
  select id into v_own from auth.users where lower(email) = 'omprakash@venturethrust.com';
  if v_own is null then v_own := v_inv; end if;
  select id into v_mgr from public.profiles where lower(email) = 'omprakash@venturethrust.com';

  -- ── Wipe ─────────────────────────────────────────────────────────────────
  select coalesce(array_agg(id), '{}') into ids from public.spaces
   where name = any(demo_names) and created_by in (v_inv, v_own);

  -- Anything ever addressed to this inbox by ANY sender is cleared too.
  -- Old test sends from other accounts are what put stray PDFs and videos
  -- in Shared with me, and they are not owned by v_inv or v_own.
  if to_regclass('public.share_link_access_logs') is not null then
    delete from public.share_link_access_logs where share_link_id in (
      select id from public.share_links
       where space_id = any(ids)
          or lower(recipient_email) = 'venturethrust@gmail.com'
          or space_id in (select id from public.spaces where created_by = v_inv));
  end if;
  if to_regclass('public.viewer_sessions') is not null then
    delete from public.viewer_sessions where space_id = any(ids);
  end if;
  if to_regclass('public.share_links') is not null then
    delete from public.share_links where space_id = any(ids)
      or lower(recipient_email) = 'venturethrust@gmail.com'
      or space_id in (select id from public.spaces where created_by = v_inv);
  end if;
  if to_regclass('public.visits') is not null then
    delete from public.visits where space_id = any(ids)
      or space_id in (select id from public.spaces where created_by = v_inv);
  end if;
  if to_regclass('public.files') is not null then
    delete from public.files where space_id = any(ids) or user_id = v_inv;
  end if;
  if to_regclass('public.folders') is not null then
    delete from public.folders where space_id = any(ids) or user_id = v_inv;
  end if;
  if to_regclass('public.spaces') is not null then
    delete from public.spaces where id = any(ids) or created_by = v_inv;
  end if;
  if to_regclass('public.dw_update_events') is not null then
    delete from public.dw_update_events where founder_id in (v_inv, v_own);
  end if;
  if to_regclass('public.dw_watchlist') is not null then
    delete from public.dw_watchlist where investor_id = v_inv;
  end if;
  if to_regclass('public.alerts') is not null then
    delete from public.alerts where user_id = v_inv;
  end if;
  if to_regclass('public.dw_offers') is not null then
    delete from public.dw_offers where lower(investor_email) = 'venturethrust@gmail.com';
  end if;

  -- ── Investor plan on ─────────────────────────────────────────────────────
  update public.profiles
     set is_investor = true, plan = 'vdr_ai', plan_status = 'active',
         plan_expires_at = now() + interval '365 days',
         dw_auto_assign = true, signup_notified = true
   where id = v_inv;

  -- ── 10 data rooms, their share link, invite and watchlist row ──────────
  for rec in
    select * from (values
      ('Nellara AgriChain',
       'Farm to retail supply chain for Kerala produce. Based in Kozhikode, Kerala.',
       'Passed at pre seed, March 2026. Right problem, wrong economics: 22 percent wastage and 8 percent gross margin meant every rupee of growth was losing money. The Kerala produce gap is real and the founder knows the Wayanad collectives personally. Come back when wastage is under 10 percent and gross margin is above 18 percent.',
       false, true, timestamptz '2026-03-12 10:40:00+05:30'),
      ('Zylo Health',
       'AI assisted radiology triage for tier 2 and tier 3 hospitals. Based in Kochi, Kerala.',
       'Strong clinical team out of Amrita and the radiologist shortage in tier 2 hospitals is real. But everything depends on CDSCO Class B clearance, which they had not even filed when we met. No point pricing a regulated device before the regulator speaks. Revisit on clearance plus one paying hospital outside Kerala.',
       true, true, timestamptz '2026-02-02 16:05:00+05:30'),
      ('Voltaneer',
       'Energy monitoring for small and mid sized factories. Based in Coimbatore, Tamil Nadu.',
       'A hardware business wearing a software badge. 76 percent of revenue was one time sensor sales and the average deal took nearly nine months because it needed a capex approval. The energy saving is real, the business model was not. Come back when recurring software is above 40 percent of revenue and the sales cycle is under 90 days.',
       false, true, timestamptz '2026-02-05 12:15:00+05:30'),
      ('Aegis Drone Systems',
       'Drone inspection for ports, transmission lines and plantation estates. Based in Kochi, Kerala.',
       'Good pilots, good imagery, no repeat business. Every rupee so far has come from one off inspections, and DGCA BVLOS permissions were still pending when we met. Inspection only becomes a business when it becomes a retainer. Revisit when at least three sites are on annual contracts and BVLOS clearance is granted.',
       false, true, timestamptz '2026-04-18 15:25:00+05:30'),
      ('Kadal Systems',
       'Satellite messaging and distress alerts for small fishing vessels. Based in Kollam, Kerala.',
       'Genuinely important product and the safety case is unarguable. My problem is who pays. Almost all current units were bought through a state subsidy scheme, so I have no evidence a boat owner pays full price from his own pocket. Show me 200 units sold without subsidy and I will look again.',
       false, true, timestamptz '2026-05-06 11:05:00+05:30'),
      ('Anvaya AI',
       'Expert reviewed Indian clinical and legal data for frontier model training. Based in Kochi, Kerala.',
       null,
       false, false, timestamptz '2026-07-29 09:20:00+05:30'),
      ('Thooval Studios',
       'AI assisted dubbing and subtitling for Indian language streaming. Based in Kozhikode, Kerala.',
       null,
       false, false, timestamptz '2026-07-27 17:45:00+05:30'),
      ('Kalpana Robotics',
       'Placement linked robotics and embedded training for tier 2 engineering colleges. Based in Kozhikode, Kerala.',
       null,
       false, false, timestamptz '2026-07-18 10:05:00+05:30'),
      ('Metricon Interconnect',
       'Precision connectors for electric vehicles and industrial automation. Based in Coimbatore, Tamil Nadu.',
       null,
       false, false, timestamptz '2026-07-21 15:30:00+05:30'),
      ('Puzha Foods',
       'Minimally processed Kerala produce for modern trade and direct to consumer. Based in Thrissur, Kerala.',
       null,
       false, false, timestamptz '2026-07-24 11:10:00+05:30')
    ) as t(nm, descr, note, quarterly, watched, added)
  loop
    s_id := gen_random_uuid();

    insert into public.spaces (id, name, title, description, created_by)
    values (s_id, rec.nm, rec.nm, rec.descr, v_own);

    -- Five top level diligence folders. No wrapper folder: the investor
    -- should land on the structure, not one folder called Root.
    insert into public.folders (id, user_id, name, space_id, parent_id, position)
    select gen_random_uuid(), v_own, fol, s_id, null, ord
      from unnest(array['01 Company Overview', '02 Financials', '03 Product and Technology', '04 Customers and Traction', '05 Legal and Compliance']) with ordinality as u(fol, ord);

    insert into public.share_links
      (id, space_id, token, is_active, email_required, recipient_email, created_by, created_at)
    values (gen_random_uuid(), s_id, encode(gen_random_bytes(16), 'hex'), true, true,
            'venturethrust@gmail.com', v_own, rec.added);

    -- Read state follows the watchlist. A startup the investor chose to
    -- follow was obviously opened, so it can never sit in Pending.
    insert into public.alerts (user_id, space_id, type, message, created_at, read_at)
    values (v_inv, s_id, 'space_shared',
            rec.nm || ' shared their data room with you.',
            rec.added, case when rec.watched then rec.added + interval '2 hours' else null end);

    if rec.watched then
      insert into public.dw_watchlist
        (id, investor_id, founder_id, space_id, file_id, startup_name, manager_id, note,
         quarterly_report, created_at)
      values (gen_random_uuid(), v_inv, v_own, s_id, null, rec.nm, v_mgr,
              rec.note, rec.quarterly, rec.added);
    end if;
  end loop;

  -- ── 130 documents, each already uploaded to the vdr-files bucket ────────
  insert into public.files
    (id, user_id, folder_id, space_id, name, type, storage_path,
     size_bytes, views, position, created_at)
  select gen_random_uuid()::text, v_own, fo.id, sp.id, t.fname, t.ftype,
         'demo/' || t.slug || '/' || t.fname,
         t.sz, t.vws, t.pos, now() - (t.age || ' days')::interval
    from (values
      ('nellara-agrichain','01 Company Overview','Nellara Pitch Deck v5.pdf','Deck',11589,0,1,3),
      ('nellara-agrichain','01 Company Overview','One Pager.pdf','PDF',3462,7,2,8),
      ('nellara-agrichain','01 Company Overview','Founder Profiles.pdf','PDF',3551,14,3,13),
      ('nellara-agrichain','01 Company Overview','Board Update Q1 FY27.pdf','PDF',3359,21,4,18),
      ('nellara-agrichain','02 Financials','Financial Model FY27.xlsx','Sheet',7261,2,1,23),
      ('nellara-agrichain','02 Financials','Unit Economics by SKU.xlsx','Sheet',5735,9,2,28),
      ('nellara-agrichain','02 Financials','Cap Table.xlsx','Sheet',5615,16,3,33),
      ('nellara-agrichain','02 Financials','GST Returns FY26.pdf','PDF',3365,23,4,38),
      ('nellara-agrichain','03 Product and Technology','Cold Chain Route Plan.pdf','PDF',3139,4,1,43),
      ('nellara-agrichain','03 Product and Technology','Wastage Tracking Method.pdf','PDF',3647,11,2,4),
      ('nellara-agrichain','03 Product and Technology','Procurement App Overview.pdf','PDF',3014,18,3,9),
      ('nellara-agrichain','04 Customers and Traction','Hotel Supply Agreements.pdf','PDF',3087,25,1,14),
      ('nellara-agrichain','04 Customers and Traction','Farmer Collective MOUs.pdf','PDF',3075,6,2,19),
      ('nellara-agrichain','04 Customers and Traction','Customer List Jul 2026.xlsx','Sheet',5839,13,3,24),
      ('nellara-agrichain','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3370,20,1,29),
      ('nellara-agrichain','05 Legal and Compliance','FSSAI License.pdf','PDF',2836,1,2,34),
      ('nellara-agrichain','05 Legal and Compliance','Shareholder Agreement.pdf','PDF',2976,8,3,39),
      ('zylo-health','01 Company Overview','Zylo Pitch Deck.pdf','Deck',11552,15,1,44),
      ('zylo-health','01 Company Overview','Clinical One Pager.pdf','PDF',3676,22,2,5),
      ('zylo-health','01 Company Overview','Founding Team.pdf','PDF',3512,3,3,10),
      ('zylo-health','02 Financials','Financial Model.xlsx','Sheet',7287,10,1,15),
      ('zylo-health','02 Financials','Per Scan Unit Economics.xlsx','Sheet',5636,17,2,20),
      ('zylo-health','02 Financials','Cap Table.xlsx','Sheet',5606,24,3,25),
      ('zylo-health','03 Product and Technology','Triage Algorithm Overview.pdf','PDF',3143,5,1,30),
      ('zylo-health','03 Product and Technology','Clinical Validation Summary.pdf','PDF',3721,12,2,35),
      ('zylo-health','03 Product and Technology','Product Overview.pdf','PDF',2872,19,3,40),
      ('zylo-health','04 Customers and Traction','Hospital Contracts.pdf','PDF',3622,0,1,45),
      ('zylo-health','04 Customers and Traction','Scan Volume Report Jul 2026.xlsx','Sheet',5880,7,2,6),
      ('zylo-health','04 Customers and Traction','Radiologist Coverage Study.pdf','PDF',2989,14,3,11),
      ('zylo-health','05 Legal and Compliance','CDSCO Filing Acknowledgement.pdf','PDF',3122,21,1,16),
      ('zylo-health','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3365,2,2,21),
      ('zylo-health','05 Legal and Compliance','Data Protection Policy.pdf','PDF',3096,9,3,26),
      ('voltaneer','01 Company Overview','Voltaneer Pitch Deck v3.pdf','Deck',11613,16,1,31),
      ('voltaneer','01 Company Overview','One Pager.pdf','PDF',3534,23,2,36),
      ('voltaneer','01 Company Overview','Team and Advisors.pdf','PDF',3507,4,3,41),
      ('voltaneer','02 Financials','Financial Model.xlsx','Sheet',7274,11,1,46),
      ('voltaneer','02 Financials','ARR Bridge FY27.xlsx','Sheet',5612,18,2,7),
      ('voltaneer','02 Financials','Cap Table.xlsx','Sheet',5610,25,3,12),
      ('voltaneer','03 Product and Technology','Sensor Spec Sheet.pdf','PDF',3508,6,1,17),
      ('voltaneer','03 Product and Technology','Dashboard Overview.pdf','PDF',3029,13,2,22),
      ('voltaneer','03 Product and Technology','Firmware Release Notes.pdf','PDF',3082,20,3,27),
      ('voltaneer','04 Customers and Traction','Annual SaaS Agreement Template.pdf','PDF',3036,1,1,32),
      ('voltaneer','04 Customers and Traction','Customer Savings Report.xlsx','Sheet',5868,8,2,37),
      ('voltaneer','04 Customers and Traction','Sales Cycle Export Jul 2026.xlsx','Sheet',5969,15,3,42),
      ('voltaneer','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3360,22,1,3),
      ('voltaneer','05 Legal and Compliance','IP Assignment Deed.pdf','PDF',3025,3,2,8),
      ('voltaneer','05 Legal and Compliance','ESOP Policy.pdf','PDF',3291,10,3,13),
      ('aegis-drone-systems','01 Company Overview','Aegis Pitch Deck.pdf','Deck',11725,17,1,18),
      ('aegis-drone-systems','01 Company Overview','Capability Statement.pdf','PDF',3120,24,2,23),
      ('aegis-drone-systems','01 Company Overview','Pilot Team Credentials.pdf','PDF',3539,5,3,28),
      ('aegis-drone-systems','02 Financials','Financial Model.xlsx','Sheet',7281,12,1,33),
      ('aegis-drone-systems','02 Financials','Project Level P and L.xlsx','Sheet',5637,19,2,38),
      ('aegis-drone-systems','02 Financials','Cap Table.xlsx','Sheet',5616,0,3,43),
      ('aegis-drone-systems','03 Product and Technology','Inspection Platform Overview.pdf','PDF',3160,7,1,4),
      ('aegis-drone-systems','03 Product and Technology','Sample Defect Report.pdf','PDF',3647,14,2,9),
      ('aegis-drone-systems','03 Product and Technology','Fleet and Payload Specs.pdf','PDF',2940,21,3,14),
      ('aegis-drone-systems','04 Customers and Traction','Port Authority Work Order.pdf','PDF',2967,2,1,19),
      ('aegis-drone-systems','04 Customers and Traction','Client List.xlsx','Sheet',5833,9,2,24),
      ('aegis-drone-systems','05 Legal and Compliance','DGCA Application Status.pdf','PDF',3033,16,1,29),
      ('aegis-drone-systems','05 Legal and Compliance','Aviation Insurance Certificate.pdf','PDF',2855,23,2,34),
      ('aegis-drone-systems','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3374,4,3,39),
      ('kadal-systems','01 Company Overview','Kadal Pitch Deck.pdf','Deck',11637,11,1,44),
      ('kadal-systems','01 Company Overview','Product One Pager.pdf','PDF',3555,18,2,5),
      ('kadal-systems','01 Company Overview','Founders.pdf','PDF',3502,25,3,10),
      ('kadal-systems','02 Financials','Financial Model.xlsx','Sheet',7264,6,1,15),
      ('kadal-systems','02 Financials','Unit Cost Breakdown.xlsx','Sheet',5666,13,2,20),
      ('kadal-systems','02 Financials','Cap Table.xlsx','Sheet',5602,20,3,25),
      ('kadal-systems','03 Product and Technology','Device Spec Sheet.pdf','PDF',3656,1,1,30),
      ('kadal-systems','03 Product and Technology','Satellite Coverage Map.pdf','PDF',3015,8,2,35),
      ('kadal-systems','03 Product and Technology','Field Trial Report.pdf','PDF',3102,15,3,40),
      ('kadal-systems','04 Customers and Traction','Unit Sales Register Jun 2026.xlsx','Sheet',5778,22,1,45),
      ('kadal-systems','04 Customers and Traction','Fisheries Dept Subsidy Order.pdf','PDF',3018,3,2,6),
      ('kadal-systems','05 Legal and Compliance','WPC Equipment License.pdf','PDF',2909,10,1,11),
      ('kadal-systems','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3356,17,2,16),
      ('kadal-systems','05 Legal and Compliance','Founder Agreement.pdf','PDF',3032,24,3,21),
      ('anvaya-ai','01 Company Overview','Anvaya Pitch Deck.pdf','Deck',11594,5,1,26),
      ('anvaya-ai','01 Company Overview','One Pager.pdf','PDF',3535,12,2,31),
      ('anvaya-ai','01 Company Overview','Founding Team.pdf','PDF',3480,19,3,36),
      ('anvaya-ai','02 Financials','Financial Model.xlsx','Sheet',7273,0,1,41),
      ('anvaya-ai','02 Financials','Unit Economics.xlsx','Sheet',5605,7,2,46),
      ('anvaya-ai','02 Financials','Cap Table.xlsx','Sheet',5557,14,3,7),
      ('anvaya-ai','03 Product and Technology','Data Pipeline and Provenance.pdf','PDF',3083,21,1,12),
      ('anvaya-ai','04 Customers and Traction','Customer Contracts.xlsx','Sheet',5662,2,1,17),
      ('anvaya-ai','04 Customers and Traction','Quality Benchmark Report.pdf','PDF',3434,9,2,22),
      ('anvaya-ai','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3347,16,1,27),
      ('anvaya-ai','05 Legal and Compliance','Reviewer and Data Agreements.pdf','PDF',2918,23,2,32),
      ('thooval-studios','01 Company Overview','Thooval Pitch Deck.pdf','Deck',11689,4,1,37),
      ('thooval-studios','01 Company Overview','One Pager.pdf','PDF',3567,11,2,42),
      ('thooval-studios','01 Company Overview','Founding Team.pdf','PDF',3473,18,3,3),
      ('thooval-studios','02 Financials','Financial Model.xlsx','Sheet',7335,25,1,8),
      ('thooval-studios','02 Financials','Unit Economics.xlsx','Sheet',5561,6,2,13),
      ('thooval-studios','02 Financials','Cap Table.xlsx','Sheet',5609,13,3,18),
      ('thooval-studios','03 Product and Technology','Localisation Pipeline.pdf','PDF',3072,20,1,23),
      ('thooval-studios','04 Customers and Traction','Customer List.xlsx','Sheet',5719,1,1,28),
      ('thooval-studios','04 Customers and Traction','Platform Delivery Record.pdf','PDF',3582,8,2,33),
      ('thooval-studios','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3366,15,1,38),
      ('thooval-studios','05 Legal and Compliance','Voice Artist Consent Framework.pdf','PDF',3087,22,2,43),
      ('kalpana-robotics','01 Company Overview','Kalpana Pitch Deck.pdf','Deck',11613,3,1,4),
      ('kalpana-robotics','01 Company Overview','One Pager.pdf','PDF',3488,10,2,9),
      ('kalpana-robotics','01 Company Overview','Founding Team.pdf','PDF',3462,17,3,14),
      ('kalpana-robotics','02 Financials','Financial Model.xlsx','Sheet',7320,24,1,19),
      ('kalpana-robotics','02 Financials','Unit Economics.xlsx','Sheet',5610,5,2,24),
      ('kalpana-robotics','02 Financials','Cap Table.xlsx','Sheet',5564,12,3,29),
      ('kalpana-robotics','03 Product and Technology','Curriculum and Lab Setup.pdf','PDF',3077,19,1,34),
      ('kalpana-robotics','04 Customers and Traction','College Contracts.xlsx','Sheet',5771,0,1,39),
      ('kalpana-robotics','04 Customers and Traction','Placement Outcomes Report.pdf','PDF',3533,7,2,44),
      ('kalpana-robotics','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3366,14,1,5),
      ('kalpana-robotics','05 Legal and Compliance','College Agreement Template.pdf','PDF',3060,21,2,10),
      ('metricon-interconnect','01 Company Overview','Metricon Pitch Deck.pdf','Deck',11672,2,1,15),
      ('metricon-interconnect','01 Company Overview','One Pager.pdf','PDF',3572,9,2,20),
      ('metricon-interconnect','01 Company Overview','Founding Team.pdf','PDF',3465,16,3,25),
      ('metricon-interconnect','02 Financials','Financial Model.xlsx','Sheet',7320,23,1,30),
      ('metricon-interconnect','02 Financials','Unit Economics.xlsx','Sheet',5686,4,2,35),
      ('metricon-interconnect','02 Financials','Cap Table.xlsx','Sheet',5610,11,3,40),
      ('metricon-interconnect','03 Product and Technology','Product Catalogue and Tooling.pdf','PDF',3017,18,1,45),
      ('metricon-interconnect','04 Customers and Traction','Customer Approvals.xlsx','Sheet',5758,25,1,6),
      ('metricon-interconnect','04 Customers and Traction','Quality and PPAP Record.pdf','PDF',3439,6,2,11),
      ('metricon-interconnect','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3381,13,1,16),
      ('metricon-interconnect','05 Legal and Compliance','Certifications and Compliance.pdf','PDF',3008,20,2,21),
      ('puzha-foods','01 Company Overview','Puzha Pitch Deck.pdf','Deck',11705,1,1,26),
      ('puzha-foods','01 Company Overview','One Pager.pdf','PDF',3540,8,2,31),
      ('puzha-foods','01 Company Overview','Founding Team.pdf','PDF',3395,15,3,36),
      ('puzha-foods','02 Financials','Financial Model.xlsx','Sheet',7332,22,1,41),
      ('puzha-foods','02 Financials','SKU Economics.xlsx','Sheet',5668,3,2,46),
      ('puzha-foods','02 Financials','Cap Table.xlsx','Sheet',5605,10,3,7),
      ('puzha-foods','03 Product and Technology','Plant and Process Overview.pdf','PDF',3114,17,1,12),
      ('puzha-foods','04 Customers and Traction','Channel Performance.xlsx','Sheet',5737,24,1,17),
      ('puzha-foods','04 Customers and Traction','Working Capital and Collections.pdf','PDF',3032,5,2,22),
      ('puzha-foods','05 Legal and Compliance','Certificate of Incorporation.pdf','PDF',3359,12,1,27),
      ('puzha-foods','05 Legal and Compliance','FSSAI and Farmer Contracts.pdf','PDF',3023,19,2,32)
    ) as t(slug, fol, fname, ftype, sz, vws, pos, age)
    join (values ('nellara-agrichain','Nellara AgriChain'), ('zylo-health','Zylo Health'), ('voltaneer','Voltaneer'), ('aegis-drone-systems','Aegis Drone Systems'), ('kadal-systems','Kadal Systems'), ('anvaya-ai','Anvaya AI'), ('thooval-studios','Thooval Studios'), ('kalpana-robotics','Kalpana Robotics'), ('metricon-interconnect','Metricon Interconnect'), ('puzha-foods','Puzha Foods')) as m(slug, nm) on m.slug = t.slug
    join public.spaces  sp on sp.name = m.nm and sp.created_by = v_own
    join public.folders fo on fo.space_id = sp.id and fo.name = t.fol;

  -- ── Founder update history behind the briefs ─────────────────────────────
  insert into public.dw_update_events (id, founder_id, space_id, file_id, file_name, event_type, created_at)
  select gen_random_uuid(), v_own, f.space_id, null, f.name, 'file_updated',
         now() - ((row_number() over (order by f.created_at desc)) || ' days')::interval
    from public.files f
    join public.spaces s on s.id = f.space_id
   where s.name = any(demo_names) and s.created_by = v_own
   limit 28;

  -- ── The two priority briefs waiting ──────────────────────────────────────
  insert into public.alerts (user_id, space_id, type, message, created_at)
  select v_inv, id, 'dw_update',
         'Priority brief ready: Nellara AgriChain has crossed both conditions from your note. Wastage 7.4 percent, gross margin 21.3 percent.',
         now() - interval '10 days'
    from public.spaces where name = 'Nellara AgriChain' and created_by = v_own limit 1;

  insert into public.alerts (user_id, space_id, type, message, created_at)
  select v_inv, id, 'dw_update',
         'Priority brief ready: Voltaneer is at 47 percent recurring revenue with a 71 day sales cycle, past both thresholds you set.',
         now() - interval '7 days'
    from public.spaces where name = 'Voltaneer' and created_by = v_own limit 1;
end $$;
